<?php
defined('BASEPATH') or exit('No direct script access allowed');

/*
 * Adds a table with names for primary subdivisions
 * ref:  http://adif.org.uk/314/ADIF_314.htm#Primary_Administrative_Subdivision
*/

class Migration_primary_subdivisions extends CI_Migration
{
	public function up()
	{
		if (!$this->db->table_exists('primary_subdivisions')) {
			$this->dbforge->add_field(array(
				'adif' => array(
					'type' => 'SMALLINT',
					'constraint' => 20,
					'unsigned' => TRUE,
				),
				'state' => array(
					'type' => 'VARCHAR',
					'constraint' => 20,
					'null' => FALSE,
				),
				'subdivision' => array(
					'type' => 'VARCHAR',
					'constraint' => 250,
					'null' => FALSE,
				),
			));
			$this->dbforge->create_table('primary_subdivisions');

			$data = array(
				array('adif' => 1, 'state' => 'NS', 'subdivision' => 'Nova Scotia'),
				array('adif' => 1, 'state' => 'QC', 'subdivision' => 'Québec'),
				array('adif' => 1, 'state' => 'ON', 'subdivision' => 'Ontario'),
				array('adif' => 1, 'state' => 'MB', 'subdivision' => 'Manitoba'),
				array('adif' => 1, 'state' => 'SK', 'subdivision' => 'Saskatchewan'),
				array('adif' => 1, 'state' => 'AB', 'subdivision' => 'Alberta'),
				array('adif' => 1, 'state' => 'BC', 'subdivision' => 'British Columbia'),
				array('adif' => 1, 'state' => 'NT', 'subdivision' => 'Northwest Territories'),
				array('adif' => 1, 'state' => 'NB', 'subdivision' => 'New Brunswick'),
				array('adif' => 1, 'state' => 'NL', 'subdivision' => 'Newfoundland and Labrador'),
				array('adif' => 1, 'state' => 'YT', 'subdivision' => 'Yukon'),
				array('adif' => 1, 'state' => 'PE', 'subdivision' => 'Prince Edward Island'),
				array('adif' => 1, 'state' => 'NU', 'subdivision' => 'Nunavut'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 5, 'state' => '001', 'subdivision' => 'Brändö'),
				array('adif' => 5, 'state' => '002', 'subdivision' => 'Eckerö'),
				array('adif' => 5, 'state' => '003', 'subdivision' => 'Finström'),
				array('adif' => 5, 'state' => '004', 'subdivision' => 'Föglö'),
				array('adif' => 5, 'state' => '005', 'subdivision' => 'Geta'),
				array('adif' => 5, 'state' => '006', 'subdivision' => 'Hammarland'),
				array('adif' => 5, 'state' => '007', 'subdivision' => 'Jomala'),
				array('adif' => 5, 'state' => '008', 'subdivision' => 'Kumlinge'),
				array('adif' => 5, 'state' => '009', 'subdivision' => 'Kökar'),
				array('adif' => 5, 'state' => '010', 'subdivision' => 'Lemland'),
				array('adif' => 5, 'state' => '011', 'subdivision' => 'Lumparland'),
				array('adif' => 5, 'state' => '012', 'subdivision' => 'Maarianhamina'),
				array('adif' => 5, 'state' => '013', 'subdivision' => 'Saltvik'),
				array('adif' => 5, 'state' => '014', 'subdivision' => 'Sottunga'),
				array('adif' => 5, 'state' => '015', 'subdivision' => 'Sund'),
				array('adif' => 5, 'state' => '016', 'subdivision' => 'Vårdö'),
				array('adif' => 5, 'state' => '051', 'subdivision' => 'Märket'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 6, 'state' => 'AK', 'subdivision' => 'Alaska'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 15, 'state' => 'UO', 'subdivision' => 'Ust-Ordynsky Autonomous Okrug'),
				array('adif' => 15, 'state' => 'AB', 'subdivision' => 'Aginsky Buryatsky Autonomous Okrug'),
				array('adif' => 15, 'state' => 'CB', 'subdivision' => 'Chelyabinsk (Chelyabinskaya oblast)'),
				array('adif' => 15, 'state' => 'SV', 'subdivision' => 'Sverdlovskaya oblast'),
				array('adif' => 15, 'state' => 'PM', 'subdivision' => 'Perm (Permskaya oblast)'),
				array('adif' => 15, 'state' => 'PM', 'subdivision' => 'Permskaya Kraj'),
				array('adif' => 15, 'state' => 'KP', 'subdivision' => 'Komi-Permyatsky Autonomous Okrug'),
				array('adif' => 15, 'state' => 'TO', 'subdivision' => 'Tomsk (Tomskaya oblast)'),
				array('adif' => 15, 'state' => 'HM', 'subdivision' => 'Khanty-Mansyisky Autonomous Okrug'),
				array('adif' => 15, 'state' => 'YN', 'subdivision' => 'Yamalo-Nenetsky Autonomous Okrug'),
				array('adif' => 15, 'state' => 'TN', 'subdivision' => 'Tyumen (Tyumenskaya oblast)'),
				array('adif' => 15, 'state' => 'OM', 'subdivision' => 'Omsk (Omskaya oblast)'),
				array('adif' => 15, 'state' => 'NS', 'subdivision' => 'Novosibirsk (Novosibirskaya oblast)'),
				array('adif' => 15, 'state' => 'KN', 'subdivision' => 'Kurgan (Kurganskaya oblast)'),
				array('adif' => 15, 'state' => 'OB', 'subdivision' => 'Orenburg (Orenburgskaya oblast)'),
				array('adif' => 15, 'state' => 'KE', 'subdivision' => 'Kemerovo (Kemerovskaya oblast)'),
				array('adif' => 15, 'state' => 'BA', 'subdivision' => 'Republic of Bashkortostan'),
				array('adif' => 15, 'state' => 'KO', 'subdivision' => 'Republic of Komi'),
				array('adif' => 15, 'state' => 'AL', 'subdivision' => 'Altaysky Kraj'),
				array('adif' => 15, 'state' => 'GA', 'subdivision' => 'Republic Gorny Altay'),
				array('adif' => 15, 'state' => 'KK', 'subdivision' => 'Krasnoyarsk (Krasnoyarsk Kraj)'),
				array('adif' => 15, 'state' => 'TM', 'subdivision' => 'Taymyr Autonomous Okrug'),
				array('adif' => 15, 'state' => 'HK', 'subdivision' => 'Khabarovsk (Khabarovsky Kraj)'),
				array('adif' => 15, 'state' => 'EA', 'subdivision' => 'Yevreyskaya Autonomous Oblast'),
				array('adif' => 15, 'state' => 'SL', 'subdivision' => 'Sakhalin (Sakhalinskaya oblast)'),
				array('adif' => 15, 'state' => 'EV', 'subdivision' => 'Evenkiysky Autonomous Okrug'),
				array('adif' => 15, 'state' => 'MG', 'subdivision' => 'Magadan (Magadanskaya oblast)'),
				array('adif' => 15, 'state' => 'AM', 'subdivision' => 'Amurskaya oblast'),
				array('adif' => 15, 'state' => 'CK', 'subdivision' => 'Chukotka Autonomous Okrug'),
				array('adif' => 15, 'state' => 'PK', 'subdivision' => 'Primorsky Kraj'),
				array('adif' => 15, 'state' => 'BU', 'subdivision' => 'Republic of Buryatia'),
				array('adif' => 15, 'state' => 'YA', 'subdivision' => 'Sakha (Yakut) Republic'),
				array('adif' => 15, 'state' => 'IR', 'subdivision' => 'Irkutsk (Irkutskaya oblast)'),
				array('adif' => 15, 'state' => 'CT', 'subdivision' => 'Zabaykalsky Kraj'),
				array('adif' => 15, 'state' => 'HA', 'subdivision' => 'Republic of Khakassia'),
				array('adif' => 15, 'state' => 'KY', 'subdivision' => 'Koryaksky Autonomous Okrug'),
				array('adif' => 15, 'state' => 'TU', 'subdivision' => 'Republic of Tuva'),
				array('adif' => 15, 'state' => 'KT', 'subdivision' => 'Kamchatka (Kamchatskaya oblast)'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 21, 'state' => 'IB', 'subdivision' => 'Baleares'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 27, 'state' => 'MI', 'subdivision' => 'Minsk (Minskaya voblasts)'),
				array('adif' => 27, 'state' => 'BR', 'subdivision' => 'Brest (Brestskaya voblasts)'),
				array('adif' => 27, 'state' => 'HR', 'subdivision' => 'Grodno (Hrodzenskaya voblasts)'),
				array('adif' => 27, 'state' => 'VI', 'subdivision' => 'Vitebsk (Vitsyebskaya voblasts)'),
				array('adif' => 27, 'state' => 'MA', 'subdivision' => 'Mogilev (Mahilyowskaya voblasts)'),
				array('adif' => 27, 'state' => 'HO', 'subdivision' => 'Gomel (Homyel skaya voblasts)'),
				array('adif' => 27, 'state' => 'HM', 'subdivision' => 'Horad Minsk'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 32, 'state' => 'CE', 'subdivision' => 'Ceuta'),
				array('adif' => 32, 'state' => 'ML', 'subdivision' => 'Melilla'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 50, 'state' => 'COL', 'subdivision' => 'Colima'),
				array('adif' => 50, 'state' => 'DF', 'subdivision' => 'Distrito Federal'),
				array('adif' => 50, 'state' => 'EMX', 'subdivision' => 'Estado de México'),
				array('adif' => 50, 'state' => 'GTO', 'subdivision' => 'Guanajuato'),
				array('adif' => 50, 'state' => 'HGO', 'subdivision' => 'Hidalgo'),
				array('adif' => 50, 'state' => 'JAL', 'subdivision' => 'Jalisco'),
				array('adif' => 50, 'state' => 'MIC', 'subdivision' => 'Michoacán de Ocampo'),
				array('adif' => 50, 'state' => 'MOR', 'subdivision' => 'Morelos'),
				array('adif' => 50, 'state' => 'NAY', 'subdivision' => 'Nayarit'),
				array('adif' => 50, 'state' => 'PUE', 'subdivision' => 'Puebla'),
				array('adif' => 50, 'state' => 'QRO', 'subdivision' => 'Querétaro de Arteaga'),
				array('adif' => 50, 'state' => 'TLX', 'subdivision' => 'Tlaxcala'),
				array('adif' => 50, 'state' => 'VER', 'subdivision' => 'Veracruz-Llave'),
				array('adif' => 50, 'state' => 'AGS', 'subdivision' => 'Aguascalientes'),
				array('adif' => 50, 'state' => 'BC', 'subdivision' => ' Baja California'),
				array('adif' => 50, 'state' => 'BCS', 'subdivision' => 'Baja California Sur'),
				array('adif' => 50, 'state' => 'CHH', 'subdivision' => 'Chihuahua'),
				array('adif' => 50, 'state' => 'COA', 'subdivision' => 'Coahuila de Zaragoza'),
				array('adif' => 50, 'state' => 'DGO', 'subdivision' => 'Durango'),
				array('adif' => 50, 'state' => 'NL', 'subdivision' => ' Nuevo Leon'),
				array('adif' => 50, 'state' => 'SLP', 'subdivision' => 'San Luis Potosí'),
				array('adif' => 50, 'state' => 'SIN', 'subdivision' => 'Sinaloa'),
				array('adif' => 50, 'state' => 'SON', 'subdivision' => 'Sonora'),
				array('adif' => 50, 'state' => 'TMS', 'subdivision' => 'Tamaulipas'),
				array('adif' => 50, 'state' => 'ZAC', 'subdivision' => 'Zacatecas'),
				array('adif' => 50, 'state' => 'CAM', 'subdivision' => 'Campeche'),
				array('adif' => 50, 'state' => 'CHS', 'subdivision' => 'Chiapas'),
				array('adif' => 50, 'state' => 'GRO', 'subdivision' => 'Guerrero'),
				array('adif' => 50, 'state' => 'OAX', 'subdivision' => 'Oaxaca'),
				array('adif' => 50, 'state' => 'QTR', 'subdivision' => 'Quintana Roo'),
				array('adif' => 50, 'state' => 'TAB', 'subdivision' => 'Tabasco'),
				array('adif' => 50, 'state' => 'YUC', 'subdivision' => 'Yucatán'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 54, 'state' => 'SP', 'subdivision' => 'City of St. Petersburg'),
				array('adif' => 54, 'state' => 'LO', 'subdivision' => 'Leningradskaya oblast'),
				array('adif' => 54, 'state' => 'KL', 'subdivision' => 'Republic of Karelia'),
				array('adif' => 54, 'state' => 'AR', 'subdivision' => 'Arkhangelsk (Arkhangelskaya oblast)'),
				array('adif' => 54, 'state' => 'NO', 'subdivision' => 'Nenetsky Autonomous Okrug'),
				array('adif' => 54, 'state' => 'VO', 'subdivision' => 'Vologda (Vologodskaya oblast)'),
				array('adif' => 54, 'state' => 'NV', 'subdivision' => 'Novgorodskaya oblast'),
				array('adif' => 54, 'state' => 'PS', 'subdivision' => 'Pskov (Pskovskaya oblast)'),
				array('adif' => 54, 'state' => 'MU', 'subdivision' => 'Murmansk (Murmanskaya oblast)'),
				array('adif' => 54, 'state' => 'MA', 'subdivision' => 'City of Moscow'),
				array('adif' => 54, 'state' => 'MO', 'subdivision' => 'Moscowskaya oblast'),
				array('adif' => 54, 'state' => 'OR', 'subdivision' => 'Oryel (Orlovskaya oblast)'),
				array('adif' => 54, 'state' => 'LP', 'subdivision' => 'Lipetsk (Lipetskaya oblast)'),
				array('adif' => 54, 'state' => 'TV', 'subdivision' => 'Tver (Tverskaya oblast)'),
				array('adif' => 54, 'state' => 'SM', 'subdivision' => 'Smolensk (Smolenskaya oblast)'),
				array('adif' => 54, 'state' => 'YR', 'subdivision' => 'Yaroslavl (Yaroslavskaya oblast)'),
				array('adif' => 54, 'state' => 'KS', 'subdivision' => 'Kostroma (Kostromskaya oblast)'),
				array('adif' => 54, 'state' => 'TL', 'subdivision' => 'Tula (Tul skaya oblast)'),
				array('adif' => 54, 'state' => 'VR', 'subdivision' => 'Voronezh (Voronezhskaya oblast)'),
				array('adif' => 54, 'state' => 'TB', 'subdivision' => 'Tambov (Tambovskaya oblast)'),
				array('adif' => 54, 'state' => 'RA', 'subdivision' => 'Ryazan (Ryazanskaya oblast)'),
				array('adif' => 54, 'state' => 'NN', 'subdivision' => 'Nizhni Novgorod (Nizhegorodskaya oblast)'),
				array('adif' => 54, 'state' => 'IV', 'subdivision' => 'Ivanovo (Ivanovskaya oblast)'),
				array('adif' => 54, 'state' => 'VL', 'subdivision' => 'Vladimir (Vladimirskaya oblast)'),
				array('adif' => 54, 'state' => 'KU', 'subdivision' => 'Kursk (Kurskaya oblast)'),
				array('adif' => 54, 'state' => 'KG', 'subdivision' => 'Kaluga (Kaluzhskaya oblast)'),
				array('adif' => 54, 'state' => 'BR', 'subdivision' => 'Bryansk (Bryanskaya oblast)'),
				array('adif' => 54, 'state' => 'BO', 'subdivision' => 'Belgorod (Belgorodskaya oblast)'),
				array('adif' => 54, 'state' => 'VG', 'subdivision' => 'Volgograd (Volgogradskaya oblast)'),
				array('adif' => 54, 'state' => 'SA', 'subdivision' => 'Saratov (Saratovskaya oblast)'),
				array('adif' => 54, 'state' => 'PE', 'subdivision' => 'Penza (Penzenskaya oblast)'),
				array('adif' => 54, 'state' => 'SR', 'subdivision' => 'Samara (Samarskaya oblast)'),
				array('adif' => 54, 'state' => 'UL', 'subdivision' => 'Ulyanovsk (Ulyanovskaya oblast)'),
				array('adif' => 54, 'state' => 'KI', 'subdivision' => 'Kirov (Kirovskaya oblast)'),
				array('adif' => 54, 'state' => 'TA', 'subdivision' => 'Republic of Tataria'),
				array('adif' => 54, 'state' => 'MR', 'subdivision' => 'Republic of Marij-El'),
				array('adif' => 54, 'state' => 'MD', 'subdivision' => 'Republic of Mordovia'),
				array('adif' => 54, 'state' => 'UD', 'subdivision' => 'Republic of Udmurtia'),
				array('adif' => 54, 'state' => 'CU', 'subdivision' => 'Republic of Chuvashia'),
				array('adif' => 54, 'state' => 'KR', 'subdivision' => 'Krasnodar (Krasnodarsky Kraj)'),
				array('adif' => 54, 'state' => 'KC', 'subdivision' => 'Republic of Karachaevo-Cherkessia'),
				array('adif' => 54, 'state' => 'ST', 'subdivision' => 'Stavropol (Stavropolsky Kraj)'),
				array('adif' => 54, 'state' => 'KM', 'subdivision' => 'Republic of Kalmykia'),
				array('adif' => 54, 'state' => 'SO', 'subdivision' => 'Republic of Northern Ossetia'),
				array('adif' => 54, 'state' => 'RO', 'subdivision' => 'Rostov-on-Don (Rostovskaya oblast)'),
				array('adif' => 54, 'state' => 'CN', 'subdivision' => 'Republic Chechnya'),
				array('adif' => 54, 'state' => 'IN', 'subdivision' => 'Republic of Ingushetia'),
				array('adif' => 54, 'state' => 'AO', 'subdivision' => 'Astrakhan (Astrakhanskaya oblast)'),
				array('adif' => 54, 'state' => 'DA', 'subdivision' => 'Republic of Daghestan'),
				array('adif' => 54, 'state' => 'KB', 'subdivision' => 'Republic of Kabardino-Balkaria'),
				array('adif' => 54, 'state' => 'AD', 'subdivision' => 'Republic of Adygeya'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 61, 'state' => 'AR', 'subdivision' => 'Arkhangelsk (Arkhangelskaya oblast)'),
				array('adif' => 61, 'state' => 'FJL', 'subdivision' => 'Franz Josef Land'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 100, 'state' => 'C', 'subdivision' => 'Capital federal (Buenos Aires City)'),
				array('adif' => 100, 'state' => 'B', 'subdivision' => 'Buenos Aires Province'),
				array('adif' => 100, 'state' => 'S', 'subdivision' => 'Santa Fe'),
				array('adif' => 100, 'state' => 'H', 'subdivision' => 'Chaco'),
				array('adif' => 100, 'state' => 'P', 'subdivision' => 'Formosa'),
				array('adif' => 100, 'state' => 'X', 'subdivision' => 'Cordoba'),
				array('adif' => 100, 'state' => 'N', 'subdivision' => 'Misiones'),
				array('adif' => 100, 'state' => 'E', 'subdivision' => 'Entre Rios'),
				array('adif' => 100, 'state' => 'T', 'subdivision' => 'Tucumán'),
				array('adif' => 100, 'state' => 'W', 'subdivision' => 'Corrientes'),
				array('adif' => 100, 'state' => 'M', 'subdivision' => 'Mendoza'),
				array('adif' => 100, 'state' => 'G', 'subdivision' => 'Santiago del Estero'),
				array('adif' => 100, 'state' => 'A', 'subdivision' => 'Salta'),
				array('adif' => 100, 'state' => 'J', 'subdivision' => 'San Juan'),
				array('adif' => 100, 'state' => 'D', 'subdivision' => 'San Luis'),
				array('adif' => 100, 'state' => 'K', 'subdivision' => 'Catamarca'),
				array('adif' => 100, 'state' => 'F', 'subdivision' => 'La Rioja'),
				array('adif' => 100, 'state' => 'Y', 'subdivision' => 'Jujuy'),
				array('adif' => 100, 'state' => 'L', 'subdivision' => 'La Pampa'),
				array('adif' => 100, 'state' => 'R', 'subdivision' => 'Rió Negro'),
				array('adif' => 100, 'state' => 'U', 'subdivision' => 'Chubut'),
				array('adif' => 100, 'state' => 'Z', 'subdivision' => 'Santa Cruz'),
				array('adif' => 100, 'state' => 'V', 'subdivision' => 'Tierra del Fuego'),
				array('adif' => 100, 'state' => 'Q', 'subdivision' => 'Neuquén'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 108, 'state' => 'ES', 'subdivision' => 'Espírito Santo'),
				array('adif' => 108, 'state' => 'GO', 'subdivision' => 'Goiás'),
				array('adif' => 108, 'state' => 'SC', 'subdivision' => 'Santa Catarina'),
				array('adif' => 108, 'state' => 'SE', 'subdivision' => 'Sergipe'),
				array('adif' => 108, 'state' => 'AL', 'subdivision' => 'Alagoas'),
				array('adif' => 108, 'state' => 'AM', 'subdivision' => 'Amazonas'),
				array('adif' => 108, 'state' => 'TO', 'subdivision' => 'Tocantins'),
				array('adif' => 108, 'state' => 'AP', 'subdivision' => 'Amapã'),
				array('adif' => 108, 'state' => 'PB', 'subdivision' => 'Paraíba'),
				array('adif' => 108, 'state' => 'MA', 'subdivision' => 'Maranhao'),
				array('adif' => 108, 'state' => 'RN', 'subdivision' => 'Rio Grande do Norte'),
				array('adif' => 108, 'state' => 'PI', 'subdivision' => 'Piaui'),
				array('adif' => 108, 'state' => 'DF', 'subdivision' => 'Oietrito Federal (Brasila)'),
				array('adif' => 108, 'state' => 'CE', 'subdivision' => 'Ceará'),
				array('adif' => 108, 'state' => 'AC', 'subdivision' => 'Acre'),
				array('adif' => 108, 'state' => 'MS', 'subdivision' => 'Mato Grosso do Sul'),
				array('adif' => 108, 'state' => 'RR', 'subdivision' => 'Roraima'),
				array('adif' => 108, 'state' => 'RO', 'subdivision' => 'Rondônia'),
				array('adif' => 108, 'state' => 'RJ', 'subdivision' => 'Rio de Janeiro'),
				array('adif' => 108, 'state' => 'SP', 'subdivision' => 'Sao Paulo'),
				array('adif' => 108, 'state' => 'RS', 'subdivision' => 'Rio Grande do Sul'),
				array('adif' => 108, 'state' => 'MG', 'subdivision' => 'Minas Gerais'),
				array('adif' => 108, 'state' => 'PR', 'subdivision' => 'Paranã'),
				array('adif' => 108, 'state' => 'BA', 'subdivision' => 'Bahia'),
				array('adif' => 108, 'state' => 'PE', 'subdivision' => 'Pernambuco'),
				array('adif' => 108, 'state' => 'PA', 'subdivision' => 'Parã'),
				array('adif' => 108, 'state' => 'MT', 'subdivision' => 'Mato Grosso'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 110, 'state' => 'HI', 'subdivision' => 'Hawaii'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 112, 'state' => 'II', 'subdivision' => 'Antofagasta'),
				array('adif' => 112, 'state' => 'III', 'subdivision' => 'Atacama'),
				array('adif' => 112, 'state' => 'I', 'subdivision' => 'Tarapacá'),
				array('adif' => 112, 'state' => 'XV', 'subdivision' => 'Arica y Parinacota'),
				array('adif' => 112, 'state' => 'IV', 'subdivision' => 'Coquimbo'),
				array('adif' => 112, 'state' => 'V', 'subdivision' => 'Valparaíso'),
				array('adif' => 112, 'state' => 'RM', 'subdivision' => 'Region Metropolitana de Santiago'),
				array('adif' => 112, 'state' => 'VI', 'subdivision' => 'Libertador General Bernardo O Higgins'),
				array('adif' => 112, 'state' => 'VII', 'subdivision' => 'Maule'),
				array('adif' => 112, 'state' => 'VIII', 'subdivision' => 'Bío-Bío'),
				array('adif' => 112, 'state' => 'IX', 'subdivision' => 'La Araucanía'),
				array('adif' => 112, 'state' => 'XIV', 'subdivision' => 'Los Ríos'),
				array('adif' => 112, 'state' => 'X', 'subdivision' => 'Los Lagos'),
				array('adif' => 112, 'state' => 'XI', 'subdivision' => 'Aisén del General Carlos Ibáñez del Campo'),
				array('adif' => 112, 'state' => 'XII', 'subdivision' => 'Magallanes'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 126, 'state' => 'KA', 'subdivision' => 'Kalingrad (Kaliningradskaya oblast)'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 132, 'state' => '16', 'subdivision' => 'Alto Paraguay'),
				array('adif' => 132, 'state' => '19', 'subdivision' => 'Boquerón'),
				array('adif' => 132, 'state' => '15', 'subdivision' => 'Presidente Hayes'),
				array('adif' => 132, 'state' => '13', 'subdivision' => 'Amambay'),
				array('adif' => 132, 'state' => '01', 'subdivision' => 'Concepción'),
				array('adif' => 132, 'state' => '14', 'subdivision' => 'Canindeyú'),
				array('adif' => 132, 'state' => '02', 'subdivision' => 'San Pedro'),
				array('adif' => 132, 'state' => 'ASU', 'subdivision' => 'Asunción'),
				array('adif' => 132, 'state' => '11', 'subdivision' => 'Central'),
				array('adif' => 132, 'state' => '03', 'subdivision' => 'Cordillera'),
				array('adif' => 132, 'state' => '09', 'subdivision' => 'Paraguarí'),
				array('adif' => 132, 'state' => '06', 'subdivision' => 'Caazapl'),
				array('adif' => 132, 'state' => '05', 'subdivision' => 'Caeguazú'),
				array('adif' => 132, 'state' => '04', 'subdivision' => 'Guairá'),
				array('adif' => 132, 'state' => '08', 'subdivision' => 'Miaiones'),
				array('adif' => 132, 'state' => '12', 'subdivision' => 'Ñeembucu'),
				array('adif' => 132, 'state' => '10', 'subdivision' => 'Alto Paraná'),
				array('adif' => 132, 'state' => '07', 'subdivision' => 'Itapua'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 137, 'state' => 'A', 'subdivision' => 'Seoul (Seoul Teugbyeolsi)'),
				array('adif' => 137, 'state' => 'N', 'subdivision' => 'Inchon (Incheon Gwang yeogsi)'),
				array('adif' => 137, 'state' => 'D', 'subdivision' => 'Kangwon-do (Gang weondo)'),
				array('adif' => 137, 'state' => 'C', 'subdivision' => 'Kyunggi-do (Gyeonggido)'),
				array('adif' => 137, 'state' => 'E', 'subdivision' => 'Choongchungbuk-do (Chungcheongbugdo)'),
				array('adif' => 137, 'state' => 'F', 'subdivision' => 'Choongchungnam-do (Chungcheongnamdo)'),
				array('adif' => 137, 'state' => 'R', 'subdivision' => 'Taejon (Daejeon Gwang yeogsi)'),
				array('adif' => 137, 'state' => 'M', 'subdivision' => 'Cheju-do (Jejudo)'),
				array('adif' => 137, 'state' => 'G', 'subdivision' => 'Chollabuk-do (Jeonrabugdo)'),
				array('adif' => 137, 'state' => 'H', 'subdivision' => 'Chollanam-do (Jeonranamdo)'),
				array('adif' => 137, 'state' => 'Q', 'subdivision' => 'Kwangju (Gwangju Gwang yeogsi)'),
				array('adif' => 137, 'state' => 'K', 'subdivision' => 'Kyungsangbuk-do (Gyeongsangbugdo)'),
				array('adif' => 137, 'state' => 'L', 'subdivision' => 'Kyungsangnam-do (Gyeongsangnamdo)'),
				array('adif' => 137, 'state' => 'B', 'subdivision' => 'Pusan (Busan Gwang yeogsi)'),
				array('adif' => 137, 'state' => 'P', 'subdivision' => 'Taegu (Daegu Gwang yeogsi)'),
				array('adif' => 137, 'state' => 'S', 'subdivision' => 'Ulsan (Ulsan Gwanq yeogsi)'),
				array('adif' => 137, 'state' => 'T', 'subdivision' => 'Sejong'),
				array('adif' => 137, 'state' => 'IS', 'subdivision' => 'Special Island'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 138, 'state' => 'KI', 'subdivision' => 'Kure Island'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 144, 'state' => 'MO', 'subdivision' => 'Montevideo'),
				array('adif' => 144, 'state' => 'CA', 'subdivision' => 'Canelones'),
				array('adif' => 144, 'state' => 'SJ', 'subdivision' => 'San José'),
				array('adif' => 144, 'state' => 'CO', 'subdivision' => 'Colonia'),
				array('adif' => 144, 'state' => 'SO', 'subdivision' => 'Soriano'),
				array('adif' => 144, 'state' => 'RN', 'subdivision' => 'Rio Negro'),
				array('adif' => 144, 'state' => 'PA', 'subdivision' => 'Paysandu'),
				array('adif' => 144, 'state' => 'SA', 'subdivision' => 'Salto'),
				array('adif' => 144, 'state' => 'AR', 'subdivision' => 'Artigsa'),
				array('adif' => 144, 'state' => 'FD', 'subdivision' => 'Florida'),
				array('adif' => 144, 'state' => 'FS', 'subdivision' => 'Flores'),
				array('adif' => 144, 'state' => 'DU', 'subdivision' => 'Durazno'),
				array('adif' => 144, 'state' => 'TA', 'subdivision' => 'Tacuarembo'),
				array('adif' => 144, 'state' => 'RV', 'subdivision' => 'Rivera'),
				array('adif' => 144, 'state' => 'MA', 'subdivision' => 'Maldonado'),
				array('adif' => 144, 'state' => 'LA', 'subdivision' => 'Lavalleja'),
				array('adif' => 144, 'state' => 'RO', 'subdivision' => 'Rocha'),
				array('adif' => 144, 'state' => 'TT', 'subdivision' => 'Treinta y Tres'),
				array('adif' => 144, 'state' => 'CL', 'subdivision' => 'Cerro Largo'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 147, 'state' => 'LH', 'subdivision' => 'Lord Howe Is'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 148, 'state' => 'AM', 'subdivision' => 'Amazonas'),
				array('adif' => 148, 'state' => 'AN', 'subdivision' => 'Anzoátegui'),
				array('adif' => 148, 'state' => 'AP', 'subdivision' => 'Apure'),
				array('adif' => 148, 'state' => 'AR', 'subdivision' => 'Aragua'),
				array('adif' => 148, 'state' => 'BA', 'subdivision' => 'Barinas'),
				array('adif' => 148, 'state' => 'BO', 'subdivision' => 'Bolívar'),
				array('adif' => 148, 'state' => 'CA', 'subdivision' => 'Carabobo'),
				array('adif' => 148, 'state' => 'CO', 'subdivision' => 'Cojedes'),
				array('adif' => 148, 'state' => 'DA', 'subdivision' => 'Delta Amacuro'),
				array('adif' => 148, 'state' => 'DC', 'subdivision' => 'Distrito Capital'),
				array('adif' => 148, 'state' => 'FA', 'subdivision' => 'Falcón'),
				array('adif' => 148, 'state' => 'GU', 'subdivision' => 'Guárico'),
				array('adif' => 148, 'state' => 'LA', 'subdivision' => 'Lara'),
				array('adif' => 148, 'state' => 'ME', 'subdivision' => 'Mérida'),
				array('adif' => 148, 'state' => 'MI', 'subdivision' => 'Miranda'),
				array('adif' => 148, 'state' => 'MO', 'subdivision' => 'Monagas'),
				array('adif' => 148, 'state' => 'NE', 'subdivision' => 'Nueva Esparta'),
				array('adif' => 148, 'state' => 'PO', 'subdivision' => 'Portuguesa'),
				array('adif' => 148, 'state' => 'SU', 'subdivision' => 'Sucre'),
				array('adif' => 148, 'state' => 'TA', 'subdivision' => 'Táchira'),
				array('adif' => 148, 'state' => 'TR', 'subdivision' => 'Trujillo'),
				array('adif' => 148, 'state' => 'VA', 'subdivision' => 'Vargas'),
				array('adif' => 148, 'state' => 'YA', 'subdivision' => 'Yaracuy'),
				array('adif' => 148, 'state' => 'ZU', 'subdivision' => 'Zulia'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 149, 'state' => 'AC', 'subdivision' => 'Açores'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 150, 'state' => 'ACT', 'subdivision' => 'Australian Capital Territory'),
				array('adif' => 150, 'state' => 'NSW', 'subdivision' => 'New South Wales'),
				array('adif' => 150, 'state' => 'VIC', 'subdivision' => 'Victoria'),
				array('adif' => 150, 'state' => 'QLD', 'subdivision' => 'Queensland'),
				array('adif' => 150, 'state' => 'SA', 'subdivision' => 'South Australia'),
				array('adif' => 150, 'state' => 'WA', 'subdivision' => 'Western Australia'),
				array('adif' => 150, 'state' => 'TAS', 'subdivision' => 'Tasmania'),
				array('adif' => 150, 'state' => 'NT', 'subdivision' => 'Northern Territory'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 151, 'state' => 'LO', 'subdivision' => 'Leningradskaya Oblast'),
				array('adif' => 151, 'state' => 'MV', 'subdivision' => 'Malyj Vysotskij'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 153, 'state' => 'MA', 'subdivision' => 'Macquarie Is'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 163, 'state' => 'NCD', 'subdivision' => 'National Capital District (Port Moresby)'),
				array('adif' => 163, 'state' => 'CPM', 'subdivision' => 'Central'),
				array('adif' => 163, 'state' => 'CPK', 'subdivision' => 'Chimbu'),
				array('adif' => 163, 'state' => 'EHG', 'subdivision' => 'Eastern Highlands'),
				array('adif' => 163, 'state' => 'EBR', 'subdivision' => 'East New Britain'),
				array('adif' => 163, 'state' => 'ESW', 'subdivision' => 'East Sepik'),
				array('adif' => 163, 'state' => 'EPW', 'subdivision' => 'Enga'),
				array('adif' => 163, 'state' => 'GPK', 'subdivision' => 'Gulf'),
				array('adif' => 163, 'state' => 'MPM', 'subdivision' => 'Madang'),
				array('adif' => 163, 'state' => 'MRL', 'subdivision' => 'Manus'),
				array('adif' => 163, 'state' => 'MBA', 'subdivision' => 'Milne Bay'),
				array('adif' => 163, 'state' => 'MPL', 'subdivision' => 'Morobe'),
				array('adif' => 163, 'state' => 'NIK', 'subdivision' => 'New Ireland'),
				array('adif' => 163, 'state' => 'NPP', 'subdivision' => 'Northern'),
				array('adif' => 163, 'state' => 'NSA', 'subdivision' => 'North Solomons'),
				array('adif' => 163, 'state' => 'SAN', 'subdivision' => 'Santaun'),
				array('adif' => 163, 'state' => 'SHM', 'subdivision' => 'Southern Highlands'),
				array('adif' => 163, 'state' => 'WPD', 'subdivision' => 'Western'),
				array('adif' => 163, 'state' => 'WHM', 'subdivision' => 'Western Highlands'),
				array('adif' => 163, 'state' => 'WBR', 'subdivision' => 'West New Britain'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 170, 'state' => 'AUK', 'subdivision' => 'Auckland'),
				array('adif' => 170, 'state' => 'BOP', 'subdivision' => 'Bay of Plenty'),
				array('adif' => 170, 'state' => 'NTL', 'subdivision' => 'Northland'),
				array('adif' => 170, 'state' => 'WKO', 'subdivision' => 'Waikato'),
				array('adif' => 170, 'state' => 'GIS', 'subdivision' => 'Gisborne'),
				array('adif' => 170, 'state' => 'HKB', 'subdivision' => 'Hawkes Bay'),
				array('adif' => 170, 'state' => 'MWT', 'subdivision' => 'Manawatu-Wanganui'),
				array('adif' => 170, 'state' => 'TKI', 'subdivision' => 'Taranaki'),
				array('adif' => 170, 'state' => 'WGN', 'subdivision' => 'Wellington'),
				array('adif' => 170, 'state' => 'CAN', 'subdivision' => 'Canterbury'),
				array('adif' => 170, 'state' => 'MBH', 'subdivision' => 'Marlborough'),
				array('adif' => 170, 'state' => 'NSN', 'subdivision' => 'Nelson'),
				array('adif' => 170, 'state' => 'TAS', 'subdivision' => 'Tasman'),
				array('adif' => 170, 'state' => 'WTC', 'subdivision' => 'West Coast'),
				array('adif' => 170, 'state' => 'OTA', 'subdivision' => 'Otago'),
				array('adif' => 170, 'state' => 'STL', 'subdivision' => 'Southland'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 177, 'state' => 'MT', 'subdivision' => 'Minami Torishima'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 192, 'state' => 'O', 'subdivision' => 'Ogasawara'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 206, 'state' => 'WC', 'subdivision' => 'Wien'),
				array('adif' => 206, 'state' => 'HA', 'subdivision' => 'Hallein'),
				array('adif' => 206, 'state' => 'JO', 'subdivision' => 'St. Johann'),
				array('adif' => 206, 'state' => 'SC', 'subdivision' => 'Salzburg'),
				array('adif' => 206, 'state' => 'SL', 'subdivision' => 'Salzburg-Land'),
				array('adif' => 206, 'state' => 'TA', 'subdivision' => 'Tamsweg'),
				array('adif' => 206, 'state' => 'ZE', 'subdivision' => 'Zell Am See'),
				array('adif' => 206, 'state' => 'AM', 'subdivision' => 'Amstetten'),
				array('adif' => 206, 'state' => 'BL', 'subdivision' => 'Bruck/Leitha'),
				array('adif' => 206, 'state' => 'BN', 'subdivision' => 'Baden'),
				array('adif' => 206, 'state' => 'GD', 'subdivision' => 'Gmünd'),
				array('adif' => 206, 'state' => 'GF', 'subdivision' => 'Gänserndorf'),
				array('adif' => 206, 'state' => 'HL', 'subdivision' => 'Hollabrunn'),
				array('adif' => 206, 'state' => 'HO', 'subdivision' => 'Horn'),
				array('adif' => 206, 'state' => 'KO', 'subdivision' => 'Korneuburg'),
				array('adif' => 206, 'state' => 'KR', 'subdivision' => 'Krems-Region'),
				array('adif' => 206, 'state' => 'KS', 'subdivision' => 'Krems'),
				array('adif' => 206, 'state' => 'LF', 'subdivision' => 'Lilienfeld'),
				array('adif' => 206, 'state' => 'MD', 'subdivision' => 'Mödling'),
				array('adif' => 206, 'state' => 'ME', 'subdivision' => 'Melk'),
				array('adif' => 206, 'state' => 'MI', 'subdivision' => 'Mistelbach'),
				array('adif' => 206, 'state' => 'NK', 'subdivision' => 'Neunkirchen'),
				array('adif' => 206, 'state' => 'PC', 'subdivision' => 'St. Pölten'),
				array('adif' => 206, 'state' => 'PL', 'subdivision' => 'St. Pölten-Land'),
				array('adif' => 206, 'state' => 'SB', 'subdivision' => 'Scheibbs'),
				array('adif' => 206, 'state' => 'SW', 'subdivision' => 'Schwechat'),
				array('adif' => 206, 'state' => 'TU', 'subdivision' => 'Tulln'),
				array('adif' => 206, 'state' => 'WB', 'subdivision' => 'Wr.Neustadt-Bezirk'),
				array('adif' => 206, 'state' => 'WN', 'subdivision' => 'Wr.Neustadt'),
				array('adif' => 206, 'state' => 'WT', 'subdivision' => 'Waidhofen/Thaya'),
				array('adif' => 206, 'state' => 'WU', 'subdivision' => 'Wien-Umgebung'),
				array('adif' => 206, 'state' => 'WY', 'subdivision' => 'Waidhofen/Ybbs'),
				array('adif' => 206, 'state' => 'ZT', 'subdivision' => 'Zwettl'),
				array('adif' => 206, 'state' => 'EC', 'subdivision' => 'Eisenstadt'),
				array('adif' => 206, 'state' => 'EU', 'subdivision' => 'Eisenstadt-Umgebung'),
				array('adif' => 206, 'state' => 'GS', 'subdivision' => 'Güssing'),
				array('adif' => 206, 'state' => 'JE', 'subdivision' => 'Jennersdorf'),
				array('adif' => 206, 'state' => 'MA', 'subdivision' => 'Mattersburg'),
				array('adif' => 206, 'state' => 'ND', 'subdivision' => 'Neusiedl/See'),
				array('adif' => 206, 'state' => 'OP', 'subdivision' => 'Oberpullendorf'),
				array('adif' => 206, 'state' => 'OW', 'subdivision' => 'Oberwart'),
				array('adif' => 206, 'state' => 'BR', 'subdivision' => 'Braunau/Inn'),
				array('adif' => 206, 'state' => 'EF', 'subdivision' => 'Eferding'),
				array('adif' => 206, 'state' => 'FR', 'subdivision' => 'Freistadt'),
				array('adif' => 206, 'state' => 'GM', 'subdivision' => 'Gmunden'),
				array('adif' => 206, 'state' => 'GR', 'subdivision' => 'Grieskirchen'),
				array('adif' => 206, 'state' => 'KI', 'subdivision' => 'Kirchdorf'),
				array('adif' => 206, 'state' => 'LC', 'subdivision' => 'Linz'),
				array('adif' => 206, 'state' => 'LL', 'subdivision' => 'Linz-Land'),
				array('adif' => 206, 'state' => 'PE', 'subdivision' => 'Perg'),
				array('adif' => 206, 'state' => 'RI', 'subdivision' => 'Ried/Innkreis'),
				array('adif' => 206, 'state' => 'RO', 'subdivision' => 'Rohrbach'),
				array('adif' => 206, 'state' => 'SD', 'subdivision' => 'Schärding'),
				array('adif' => 206, 'state' => 'SE', 'subdivision' => 'Steyr-Land'),
				array('adif' => 206, 'state' => 'SR', 'subdivision' => 'Steyr'),
				array('adif' => 206, 'state' => 'UU', 'subdivision' => 'Urfahr'),
				array('adif' => 206, 'state' => 'VB', 'subdivision' => 'Vöcklabruck'),
				array('adif' => 206, 'state' => 'WE', 'subdivision' => 'Wels'),
				array('adif' => 206, 'state' => 'WL', 'subdivision' => 'Wels-Land'),
				array('adif' => 206, 'state' => 'BA', 'subdivision' => 'Bad Aussee'),
				array('adif' => 206, 'state' => 'BM', 'subdivision' => 'Bruck/Mur'),
				array('adif' => 206, 'state' => 'BM', 'subdivision' => 'Bruck-Mürzzuschlag'),
				array('adif' => 206, 'state' => 'DL', 'subdivision' => 'Deutschlandsberg'),
				array('adif' => 206, 'state' => 'FB', 'subdivision' => 'Feldbach'),
				array('adif' => 206, 'state' => 'FF', 'subdivision' => 'Fürstenfeld'),
				array('adif' => 206, 'state' => 'GB', 'subdivision' => 'Gröbming'),
				array('adif' => 206, 'state' => 'GC', 'subdivision' => 'Graz'),
				array('adif' => 206, 'state' => 'GU', 'subdivision' => 'Graz-Umgebung'),
				array('adif' => 206, 'state' => 'HB', 'subdivision' => 'Hartberg'),
				array('adif' => 206, 'state' => 'HF', 'subdivision' => 'Hartberg-Fürstenfeld'),
				array('adif' => 206, 'state' => 'JU', 'subdivision' => 'Judenburg'),
				array('adif' => 206, 'state' => 'KF', 'subdivision' => 'Knittelfeld'),
				array('adif' => 206, 'state' => 'LB', 'subdivision' => 'Leibnitz'),
				array('adif' => 206, 'state' => 'LE', 'subdivision' => 'Leoben'),
				array('adif' => 206, 'state' => 'LI', 'subdivision' => 'Liezen'),
				array('adif' => 206, 'state' => 'LN', 'subdivision' => 'Leoben-Land'),
				array('adif' => 206, 'state' => 'MT', 'subdivision' => 'Murtal'),
				array('adif' => 206, 'state' => 'MU', 'subdivision' => 'Murau'),
				array('adif' => 206, 'state' => 'MZ', 'subdivision' => 'Mürzzuschlag'),
				array('adif' => 206, 'state' => 'RA', 'subdivision' => 'Radkersburg'),
				array('adif' => 206, 'state' => 'SO', 'subdivision' => 'Südoststeiermark'),
				array('adif' => 206, 'state' => 'VO', 'subdivision' => 'Voitsberg'),
				array('adif' => 206, 'state' => 'WZ', 'subdivision' => 'Weiz'),
				array('adif' => 206, 'state' => 'IC', 'subdivision' => 'Innsbruck'),
				array('adif' => 206, 'state' => 'IL', 'subdivision' => 'Innsbruck-Land'),
				array('adif' => 206, 'state' => 'IM', 'subdivision' => 'Imst'),
				array('adif' => 206, 'state' => 'KB', 'subdivision' => 'Kitzbühel'),
				array('adif' => 206, 'state' => 'KU', 'subdivision' => 'Kufstein'),
				array('adif' => 206, 'state' => 'LA', 'subdivision' => 'Landeck'),
				array('adif' => 206, 'state' => 'LZ', 'subdivision' => 'Lienz'),
				array('adif' => 206, 'state' => 'RE', 'subdivision' => 'Reutte'),
				array('adif' => 206, 'state' => 'SZ', 'subdivision' => 'Schwaz'),
				array('adif' => 206, 'state' => 'FE', 'subdivision' => 'Feldkirchen'),
				array('adif' => 206, 'state' => 'HE', 'subdivision' => 'Hermagor'),
				array('adif' => 206, 'state' => 'KC', 'subdivision' => 'Klagenfurt'),
				array('adif' => 206, 'state' => 'KL', 'subdivision' => 'Klagenfurt-Land'),
				array('adif' => 206, 'state' => 'SP', 'subdivision' => 'Spittal/Drau'),
				array('adif' => 206, 'state' => 'SV', 'subdivision' => 'St.Veit/Glan'),
				array('adif' => 206, 'state' => 'VI', 'subdivision' => 'Villach'),
				array('adif' => 206, 'state' => 'VK', 'subdivision' => 'Völkermarkt'),
				array('adif' => 206, 'state' => 'VL', 'subdivision' => 'Villach-Land'),
				array('adif' => 206, 'state' => 'WO', 'subdivision' => 'Wolfsberg'),
				array('adif' => 206, 'state' => 'BC', 'subdivision' => 'Bregenz'),
				array('adif' => 206, 'state' => 'BZ', 'subdivision' => 'Bludenz'),
				array('adif' => 206, 'state' => 'DO', 'subdivision' => 'Dornbirn'),
				array('adif' => 206, 'state' => 'FK', 'subdivision' => 'Feldkirch'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 209, 'state' => 'AN', 'subdivision' => 'Antwerpen'),
				array('adif' => 209, 'state' => 'BR', 'subdivision' => 'Brussels'),
				array('adif' => 209, 'state' => 'BW', 'subdivision' => 'Brabant Wallon'),
				array('adif' => 209, 'state' => 'HT', 'subdivision' => 'Hainaut'),
				array('adif' => 209, 'state' => 'LB', 'subdivision' => 'Limburg'),
				array('adif' => 209, 'state' => 'LG', 'subdivision' => 'Liêge'),
				array('adif' => 209, 'state' => 'NM', 'subdivision' => 'Namur'),
				array('adif' => 209, 'state' => 'LU', 'subdivision' => 'Luxembourg'),
				array('adif' => 209, 'state' => 'OV', 'subdivision' => 'Oost-Vlaanderen'),
				array('adif' => 209, 'state' => 'VB', 'subdivision' => 'Vlaams Brabant'),
				array('adif' => 209, 'state' => 'WV', 'subdivision' => 'West-Vlaanderen'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 212, 'state' => 'BU', 'subdivision' => 'Burgas'),
				array('adif' => 212, 'state' => 'SL', 'subdivision' => 'Sliven'),
				array('adif' => 212, 'state' => 'YA', 'subdivision' => 'Yambol (Jambol)'),
				array('adif' => 212, 'state' => 'SO', 'subdivision' => 'Sofija Grad'),
				array('adif' => 212, 'state' => 'HA', 'subdivision' => 'Haskovo'),
				array('adif' => 212, 'state' => 'KA', 'subdivision' => 'Kărdžali'),
				array('adif' => 212, 'state' => 'SZ', 'subdivision' => 'Stara Zagora'),
				array('adif' => 212, 'state' => 'PA', 'subdivision' => 'Pazardžik'),
				array('adif' => 212, 'state' => 'PD', 'subdivision' => 'Plovdiv'),
				array('adif' => 212, 'state' => 'SM', 'subdivision' => 'Smoljan'),
				array('adif' => 212, 'state' => 'BL', 'subdivision' => 'Blagoevgrad'),
				array('adif' => 212, 'state' => 'KD', 'subdivision' => 'Kjustendil'),
				array('adif' => 212, 'state' => 'PK', 'subdivision' => 'Pernik'),
				array('adif' => 212, 'state' => 'SF', 'subdivision' => 'Sofija (Sofia)'),
				array('adif' => 212, 'state' => 'GA', 'subdivision' => 'Gabrovo'),
				array('adif' => 212, 'state' => 'LV', 'subdivision' => 'Loveč (Lovech)'),
				array('adif' => 212, 'state' => 'PL', 'subdivision' => 'Pleven'),
				array('adif' => 212, 'state' => 'VT', 'subdivision' => 'Veliko Tărnovo'),
				array('adif' => 212, 'state' => 'MN', 'subdivision' => 'Montana'),
				array('adif' => 212, 'state' => 'VD', 'subdivision' => 'Vidin'),
				array('adif' => 212, 'state' => 'VR', 'subdivision' => 'Vraca'),
				array('adif' => 212, 'state' => 'RZ', 'subdivision' => 'Razgrad'),
				array('adif' => 212, 'state' => 'RS', 'subdivision' => 'Ruse'),
				array('adif' => 212, 'state' => 'SS', 'subdivision' => 'Silistra'),
				array('adif' => 212, 'state' => 'TA', 'subdivision' => 'Tărgovište'),
				array('adif' => 212, 'state' => 'DO', 'subdivision' => 'Dobrič'),
				array('adif' => 212, 'state' => 'SN', 'subdivision' => 'Šumen'),
				array('adif' => 212, 'state' => 'VN', 'subdivision' => 'Varna'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 214, 'state' => '2A', 'subdivision' => 'Corse-du-Sud'),
				array('adif' => 214, 'state' => '2B', 'subdivision' => 'Haute-Corse'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 221, 'state' => '015', 'subdivision' => 'Koebenhavns amt'),
				array('adif' => 221, 'state' => '020', 'subdivision' => 'Frederiksborg amt'),
				array('adif' => 221, 'state' => '025', 'subdivision' => 'Roskilde amt'),
				array('adif' => 221, 'state' => '030', 'subdivision' => 'Vestsjaellands amt'),
				array('adif' => 221, 'state' => '035', 'subdivision' => 'Storstrøm amt (Storstroems)'),
				array('adif' => 221, 'state' => '040', 'subdivision' => 'Bornholms amt'),
				array('adif' => 221, 'state' => '042', 'subdivision' => 'Fyns amt'),
				array('adif' => 221, 'state' => '050', 'subdivision' => 'Sínderjylland amt (Sydjyllands)'),
				array('adif' => 221, 'state' => '055', 'subdivision' => 'Ribe amt'),
				array('adif' => 221, 'state' => '060', 'subdivision' => 'Vejle amt'),
				array('adif' => 221, 'state' => '065', 'subdivision' => 'Ringkøbing amt (Ringkoebing)'),
				array('adif' => 221, 'state' => '070', 'subdivision' => 'Århus amt (Aarhus)'),
				array('adif' => 221, 'state' => '076', 'subdivision' => 'Viborg amt'),
				array('adif' => 221, 'state' => '080', 'subdivision' => 'Nordjyllands amt'),
				array('adif' => 221, 'state' => '101', 'subdivision' => 'Copenhagen City'),
				array('adif' => 221, 'state' => '147', 'subdivision' => 'Frederiksberg'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 224, 'state' => '100', 'subdivision' => 'Somero'),
				array('adif' => 224, 'state' => '102', 'subdivision' => 'Alastaro'),
				array('adif' => 224, 'state' => '103', 'subdivision' => 'Askainen'),
				array('adif' => 224, 'state' => '104', 'subdivision' => 'Aura'),
				array('adif' => 224, 'state' => '105', 'subdivision' => 'Dragsfjärd'),
				array('adif' => 224, 'state' => '106', 'subdivision' => 'Eura'),
				array('adif' => 224, 'state' => '107', 'subdivision' => 'Eurajoki'),
				array('adif' => 224, 'state' => '108', 'subdivision' => 'Halikko'),
				array('adif' => 224, 'state' => '109', 'subdivision' => 'Harjavalta'),
				array('adif' => 224, 'state' => '110', 'subdivision' => 'Honkajoki'),
				array('adif' => 224, 'state' => '111', 'subdivision' => 'Houtskari'),
				array('adif' => 224, 'state' => '112', 'subdivision' => 'Huittinen'),
				array('adif' => 224, 'state' => '115', 'subdivision' => 'Iniö'),
				array('adif' => 224, 'state' => '116', 'subdivision' => 'Jämijärvi'),
				array('adif' => 224, 'state' => '117', 'subdivision' => 'Kaarina'),
				array('adif' => 224, 'state' => '119', 'subdivision' => 'Kankaanpää'),
				array('adif' => 224, 'state' => '120', 'subdivision' => 'Karinainen'),
				array('adif' => 224, 'state' => '122', 'subdivision' => 'Karvia'),
				array('adif' => 224, 'state' => '123', 'subdivision' => 'Äetsä'),
				array('adif' => 224, 'state' => '124', 'subdivision' => 'Kemiö'),
				array('adif' => 224, 'state' => '126', 'subdivision' => 'Kiikala'),
				array('adif' => 224, 'state' => '128', 'subdivision' => 'Kiikoinen'),
				array('adif' => 224, 'state' => '129', 'subdivision' => 'Kisko'),
				array('adif' => 224, 'state' => '130', 'subdivision' => 'Kiukainen'),
				array('adif' => 224, 'state' => '131', 'subdivision' => 'Kodisjoki'),
				array('adif' => 224, 'state' => '132', 'subdivision' => 'Kokemäki'),
				array('adif' => 224, 'state' => '133', 'subdivision' => 'Korppoo'),
				array('adif' => 224, 'state' => '134', 'subdivision' => 'Koski tl'),
				array('adif' => 224, 'state' => '135', 'subdivision' => 'Kullaa'),
				array('adif' => 224, 'state' => '136', 'subdivision' => 'Kustavi'),
				array('adif' => 224, 'state' => '137', 'subdivision' => 'Kuusjoki'),
				array('adif' => 224, 'state' => '138', 'subdivision' => 'Köyliö'),
				array('adif' => 224, 'state' => '139', 'subdivision' => 'Laitila'),
				array('adif' => 224, 'state' => '140', 'subdivision' => 'Lappi'),
				array('adif' => 224, 'state' => '141', 'subdivision' => 'Lavia'),
				array('adif' => 224, 'state' => '142', 'subdivision' => 'Lemu'),
				array('adif' => 224, 'state' => '143', 'subdivision' => 'Lieto'),
				array('adif' => 224, 'state' => '144', 'subdivision' => 'Loimaa'),
				array('adif' => 224, 'state' => '145', 'subdivision' => 'Loimaan kunta'),
				array('adif' => 224, 'state' => '147', 'subdivision' => 'Luvia'),
				array('adif' => 224, 'state' => '148', 'subdivision' => 'Marttila'),
				array('adif' => 224, 'state' => '149', 'subdivision' => 'Masku'),
				array('adif' => 224, 'state' => '150', 'subdivision' => 'Mellilä'),
				array('adif' => 224, 'state' => '151', 'subdivision' => 'Merikarvia'),
				array('adif' => 224, 'state' => '152', 'subdivision' => 'Merimasku'),
				array('adif' => 224, 'state' => '154', 'subdivision' => 'Mietoinen'),
				array('adif' => 224, 'state' => '156', 'subdivision' => 'Muurla'),
				array('adif' => 224, 'state' => '157', 'subdivision' => 'Mynämäki'),
				array('adif' => 224, 'state' => '158', 'subdivision' => 'Naantali'),
				array('adif' => 224, 'state' => '159', 'subdivision' => 'Nakkila'),
				array('adif' => 224, 'state' => '160', 'subdivision' => 'Nauvo'),
				array('adif' => 224, 'state' => '161', 'subdivision' => 'Noormarkku'),
				array('adif' => 224, 'state' => '162', 'subdivision' => 'Nousiainen'),
				array('adif' => 224, 'state' => '163', 'subdivision' => 'Oripää'),
				array('adif' => 224, 'state' => '164', 'subdivision' => 'Paimio'),
				array('adif' => 224, 'state' => '165', 'subdivision' => 'Parainen'),
				array('adif' => 224, 'state' => '167', 'subdivision' => 'Perniö'),
				array('adif' => 224, 'state' => '168', 'subdivision' => 'Pertteli'),
				array('adif' => 224, 'state' => '169', 'subdivision' => 'Piikkiö'),
				array('adif' => 224, 'state' => '170', 'subdivision' => 'Pomarkku'),
				array('adif' => 224, 'state' => '171', 'subdivision' => 'Pori'),
				array('adif' => 224, 'state' => '172', 'subdivision' => 'Punkalaidun'),
				array('adif' => 224, 'state' => '173', 'subdivision' => 'Pyhäranta'),
				array('adif' => 224, 'state' => '174', 'subdivision' => 'Pöytyä'),
				array('adif' => 224, 'state' => '175', 'subdivision' => 'Raisio'),
				array('adif' => 224, 'state' => '176', 'subdivision' => 'Rauma'),
				array('adif' => 224, 'state' => '178', 'subdivision' => 'Rusko'),
				array('adif' => 224, 'state' => '179', 'subdivision' => 'Rymättylä'),
				array('adif' => 224, 'state' => '180', 'subdivision' => 'Salo'),
				array('adif' => 224, 'state' => '181', 'subdivision' => 'Sauvo'),
				array('adif' => 224, 'state' => '182', 'subdivision' => 'Siikainen'),
				array('adif' => 224, 'state' => '183', 'subdivision' => 'Suodenniemi'),
				array('adif' => 224, 'state' => '184', 'subdivision' => 'Suomusjärvi'),
				array('adif' => 224, 'state' => '185', 'subdivision' => 'Säkylä'),
				array('adif' => 224, 'state' => '186', 'subdivision' => 'Särkisalo'),
				array('adif' => 224, 'state' => '187', 'subdivision' => 'Taivassalo'),
				array('adif' => 224, 'state' => '188', 'subdivision' => 'Tarvasjoki'),
				array('adif' => 224, 'state' => '189', 'subdivision' => 'Turku'),
				array('adif' => 224, 'state' => '190', 'subdivision' => 'Ulvila'),
				array('adif' => 224, 'state' => '191', 'subdivision' => 'Uusikaupunki'),
				array('adif' => 224, 'state' => '192', 'subdivision' => 'Vahto'),
				array('adif' => 224, 'state' => '193', 'subdivision' => 'Vammala'),
				array('adif' => 224, 'state' => '194', 'subdivision' => 'Vampula'),
				array('adif' => 224, 'state' => '195', 'subdivision' => 'Vehmaa'),
				array('adif' => 224, 'state' => '196', 'subdivision' => 'Velkua'),
				array('adif' => 224, 'state' => '198', 'subdivision' => 'Västanfjärd'),
				array('adif' => 224, 'state' => '199', 'subdivision' => 'Yläne'),
				array('adif' => 224, 'state' => '201', 'subdivision' => 'Artjärvi'),
				array('adif' => 224, 'state' => '202', 'subdivision' => 'Askola'),
				array('adif' => 224, 'state' => '204', 'subdivision' => 'Espoo'),
				array('adif' => 224, 'state' => '205', 'subdivision' => 'Hanko'),
				array('adif' => 224, 'state' => '206', 'subdivision' => 'Helsinki'),
				array('adif' => 224, 'state' => '207', 'subdivision' => 'Hyvinkää'),
				array('adif' => 224, 'state' => '208', 'subdivision' => 'Inkoo'),
				array('adif' => 224, 'state' => '209', 'subdivision' => 'Järvenpää'),
				array('adif' => 224, 'state' => '210', 'subdivision' => 'Karjaa'),
				array('adif' => 224, 'state' => '211', 'subdivision' => 'Karjalohja'),
				array('adif' => 224, 'state' => '212', 'subdivision' => 'Karkkila'),
				array('adif' => 224, 'state' => '213', 'subdivision' => 'Kauniainen'),
				array('adif' => 224, 'state' => '214', 'subdivision' => 'Kerava'),
				array('adif' => 224, 'state' => '215', 'subdivision' => 'Kirkkonummi'),
				array('adif' => 224, 'state' => '216', 'subdivision' => 'Lapinjärvi'),
				array('adif' => 224, 'state' => '217', 'subdivision' => 'Liljendal'),
				array('adif' => 224, 'state' => '218', 'subdivision' => 'Lohjan kaupunki'),
				array('adif' => 224, 'state' => '220', 'subdivision' => 'Loviisa'),
				array('adif' => 224, 'state' => '221', 'subdivision' => 'Myrskylä'),
				array('adif' => 224, 'state' => '222', 'subdivision' => 'Mäntsälä'),
				array('adif' => 224, 'state' => '223', 'subdivision' => 'Nummi-Pusula'),
				array('adif' => 224, 'state' => '224', 'subdivision' => 'Nurmijärvi'),
				array('adif' => 224, 'state' => '225', 'subdivision' => 'Orimattila'),
				array('adif' => 224, 'state' => '226', 'subdivision' => 'Pernaja'),
				array('adif' => 224, 'state' => '227', 'subdivision' => 'Pohja'),
				array('adif' => 224, 'state' => '228', 'subdivision' => 'Pornainen'),
				array('adif' => 224, 'state' => '229', 'subdivision' => 'Porvoo'),
				array('adif' => 224, 'state' => '231', 'subdivision' => 'Pukkila'),
				array('adif' => 224, 'state' => '233', 'subdivision' => 'Ruotsinpyhtää'),
				array('adif' => 224, 'state' => '234', 'subdivision' => 'Sammatti'),
				array('adif' => 224, 'state' => '235', 'subdivision' => 'Sipoo'),
				array('adif' => 224, 'state' => '236', 'subdivision' => 'Siuntio'),
				array('adif' => 224, 'state' => '238', 'subdivision' => 'Tammisaari'),
				array('adif' => 224, 'state' => '241', 'subdivision' => 'Tuusula'),
				array('adif' => 224, 'state' => '242', 'subdivision' => 'Vantaa'),
				array('adif' => 224, 'state' => '243', 'subdivision' => 'Vihti'),
				array('adif' => 224, 'state' => '301', 'subdivision' => 'Asikkala'),
				array('adif' => 224, 'state' => '303', 'subdivision' => 'Forssa'),
				array('adif' => 224, 'state' => '304', 'subdivision' => 'Hattula'),
				array('adif' => 224, 'state' => '305', 'subdivision' => 'Hauho'),
				array('adif' => 224, 'state' => '306', 'subdivision' => 'Hausjärvi'),
				array('adif' => 224, 'state' => '307', 'subdivision' => 'Hollola'),
				array('adif' => 224, 'state' => '308', 'subdivision' => 'Humppila'),
				array('adif' => 224, 'state' => '309', 'subdivision' => 'Hämeenlinna'),
				array('adif' => 224, 'state' => '310', 'subdivision' => 'Janakkala'),
				array('adif' => 224, 'state' => '311', 'subdivision' => 'Jokioinen'),
				array('adif' => 224, 'state' => '312', 'subdivision' => 'Juupajoki'),
				array('adif' => 224, 'state' => '313', 'subdivision' => 'Kalvola'),
				array('adif' => 224, 'state' => '314', 'subdivision' => 'Kangasala'),
				array('adif' => 224, 'state' => '315', 'subdivision' => 'Hämeenkoski'),
				array('adif' => 224, 'state' => '316', 'subdivision' => 'Kuhmalahti'),
				array('adif' => 224, 'state' => '318', 'subdivision' => 'Kuru'),
				array('adif' => 224, 'state' => '319', 'subdivision' => 'Kylmäkoski'),
				array('adif' => 224, 'state' => '320', 'subdivision' => 'Kärkölä'),
				array('adif' => 224, 'state' => '321', 'subdivision' => 'Lahti'),
				array('adif' => 224, 'state' => '322', 'subdivision' => 'Lammi'),
				array('adif' => 224, 'state' => '323', 'subdivision' => 'Lempäälä'),
				array('adif' => 224, 'state' => '324', 'subdivision' => 'Loppi'),
				array('adif' => 224, 'state' => '325', 'subdivision' => 'Luopioinen'),
				array('adif' => 224, 'state' => '326', 'subdivision' => 'Längelmäki'),
				array('adif' => 224, 'state' => '327', 'subdivision' => 'Mänttä'),
				array('adif' => 224, 'state' => '328', 'subdivision' => 'Nastola'),
				array('adif' => 224, 'state' => '329', 'subdivision' => 'Nokia'),
				array('adif' => 224, 'state' => '330', 'subdivision' => 'Orivesi'),
				array('adif' => 224, 'state' => '331', 'subdivision' => 'Padasjoki'),
				array('adif' => 224, 'state' => '332', 'subdivision' => 'Pirkkala'),
				array('adif' => 224, 'state' => '333', 'subdivision' => 'Pälkäne'),
				array('adif' => 224, 'state' => '334', 'subdivision' => 'Renko'),
				array('adif' => 224, 'state' => '335', 'subdivision' => 'Riihimäki'),
				array('adif' => 224, 'state' => '336', 'subdivision' => 'Ruovesi'),
				array('adif' => 224, 'state' => '337', 'subdivision' => 'Sahalahti'),
				array('adif' => 224, 'state' => '340', 'subdivision' => 'Tammela'),
				array('adif' => 224, 'state' => '341', 'subdivision' => 'Tampere'),
				array('adif' => 224, 'state' => '342', 'subdivision' => 'Toijala'),
				array('adif' => 224, 'state' => '344', 'subdivision' => 'Tuulos'),
				array('adif' => 224, 'state' => '345', 'subdivision' => 'Urjala'),
				array('adif' => 224, 'state' => '346', 'subdivision' => 'Valkeakoski'),
				array('adif' => 224, 'state' => '347', 'subdivision' => 'Vesilahti'),
				array('adif' => 224, 'state' => '348', 'subdivision' => 'Viiala'),
				array('adif' => 224, 'state' => '349', 'subdivision' => 'Vilppula'),
				array('adif' => 224, 'state' => '350', 'subdivision' => 'Virrat'),
				array('adif' => 224, 'state' => '351', 'subdivision' => 'Ylöjärvi'),
				array('adif' => 224, 'state' => '352', 'subdivision' => 'Ypäjä'),
				array('adif' => 224, 'state' => '353', 'subdivision' => 'Hämeenkyrö'),
				array('adif' => 224, 'state' => '354', 'subdivision' => 'Ikaalinen'),
				array('adif' => 224, 'state' => '355', 'subdivision' => 'Kihniö'),
				array('adif' => 224, 'state' => '356', 'subdivision' => 'Mouhijärvi'),
				array('adif' => 224, 'state' => '357', 'subdivision' => 'Parkano'),
				array('adif' => 224, 'state' => '358', 'subdivision' => 'Viljakkala'),
				array('adif' => 224, 'state' => '402', 'subdivision' => 'Enonkoski'),
				array('adif' => 224, 'state' => '403', 'subdivision' => 'Hartola'),
				array('adif' => 224, 'state' => '404', 'subdivision' => 'Haukivuori'),
				array('adif' => 224, 'state' => '405', 'subdivision' => 'Heinola'),
				array('adif' => 224, 'state' => '407', 'subdivision' => 'Heinävesi'),
				array('adif' => 224, 'state' => '408', 'subdivision' => 'Hirvensalmi'),
				array('adif' => 224, 'state' => '409', 'subdivision' => 'Joroinen'),
				array('adif' => 224, 'state' => '410', 'subdivision' => 'Juva'),
				array('adif' => 224, 'state' => '411', 'subdivision' => 'Jäppilä'),
				array('adif' => 224, 'state' => '412', 'subdivision' => 'Kangaslampi'),
				array('adif' => 224, 'state' => '413', 'subdivision' => 'Kangasniemi'),
				array('adif' => 224, 'state' => '414', 'subdivision' => 'Kerimäki'),
				array('adif' => 224, 'state' => '415', 'subdivision' => 'Mikkeli'),
				array('adif' => 224, 'state' => '417', 'subdivision' => 'Mäntyharju'),
				array('adif' => 224, 'state' => '418', 'subdivision' => 'Pertunmaa'),
				array('adif' => 224, 'state' => '419', 'subdivision' => 'Pieksämäki'),
				array('adif' => 224, 'state' => '420', 'subdivision' => 'Pieksänmaa'),
				array('adif' => 224, 'state' => '421', 'subdivision' => 'Punkaharju'),
				array('adif' => 224, 'state' => '422', 'subdivision' => 'Puumala'),
				array('adif' => 224, 'state' => '423', 'subdivision' => 'Rantasalmi'),
				array('adif' => 224, 'state' => '424', 'subdivision' => 'Ristiina'),
				array('adif' => 224, 'state' => '425', 'subdivision' => 'Savonlinna'),
				array('adif' => 224, 'state' => '426', 'subdivision' => 'Savonranta'),
				array('adif' => 224, 'state' => '427', 'subdivision' => 'Sulkava'),
				array('adif' => 224, 'state' => '428', 'subdivision' => 'Sysmä'),
				array('adif' => 224, 'state' => '502', 'subdivision' => 'Elimäki'),
				array('adif' => 224, 'state' => '503', 'subdivision' => 'Hamina'),
				array('adif' => 224, 'state' => '504', 'subdivision' => 'Iitti'),
				array('adif' => 224, 'state' => '505', 'subdivision' => 'Imatra'),
				array('adif' => 224, 'state' => '506', 'subdivision' => 'Jaala'),
				array('adif' => 224, 'state' => '507', 'subdivision' => 'Joutseno'),
				array('adif' => 224, 'state' => '509', 'subdivision' => 'Kotka'),
				array('adif' => 224, 'state' => '510', 'subdivision' => 'Kouvola'),
				array('adif' => 224, 'state' => '511', 'subdivision' => 'Kuusankoski'),
				array('adif' => 224, 'state' => '513', 'subdivision' => 'Lappeenranta'),
				array('adif' => 224, 'state' => '514', 'subdivision' => 'Lemi'),
				array('adif' => 224, 'state' => '515', 'subdivision' => 'Luumäki'),
				array('adif' => 224, 'state' => '516', 'subdivision' => 'Miehikkälä'),
				array('adif' => 224, 'state' => '518', 'subdivision' => 'Parikkala'),
				array('adif' => 224, 'state' => '519', 'subdivision' => 'Pyhtää'),
				array('adif' => 224, 'state' => '520', 'subdivision' => 'Rautjärvi'),
				array('adif' => 224, 'state' => '521', 'subdivision' => 'Ruokolahti'),
				array('adif' => 224, 'state' => '522', 'subdivision' => 'Saari'),
				array('adif' => 224, 'state' => '523', 'subdivision' => 'Savitaipale'),
				array('adif' => 224, 'state' => '525', 'subdivision' => 'Suomenniemi'),
				array('adif' => 224, 'state' => '526', 'subdivision' => 'Taipalsaari'),
				array('adif' => 224, 'state' => '527', 'subdivision' => 'Uukuniemi'),
				array('adif' => 224, 'state' => '528', 'subdivision' => 'Valkeala'),
				array('adif' => 224, 'state' => '530', 'subdivision' => 'Virolahti'),
				array('adif' => 224, 'state' => '531', 'subdivision' => 'Ylämaa'),
				array('adif' => 224, 'state' => '532', 'subdivision' => 'Anjalankoski'),
				array('adif' => 224, 'state' => '601', 'subdivision' => 'Alahärmä'),
				array('adif' => 224, 'state' => '602', 'subdivision' => 'Alajärvi'),
				array('adif' => 224, 'state' => '603', 'subdivision' => 'Alavus'),
				array('adif' => 224, 'state' => '604', 'subdivision' => 'Evijärvi'),
				array('adif' => 224, 'state' => '605', 'subdivision' => 'Halsua'),
				array('adif' => 224, 'state' => '606', 'subdivision' => 'Hankasalmi'),
				array('adif' => 224, 'state' => '607', 'subdivision' => 'Himanka'),
				array('adif' => 224, 'state' => '608', 'subdivision' => 'Ilmajoki'),
				array('adif' => 224, 'state' => '609', 'subdivision' => 'Isojoki'),
				array('adif' => 224, 'state' => '610', 'subdivision' => 'Isokyrö'),
				array('adif' => 224, 'state' => '611', 'subdivision' => 'Jalasjärvi'),
				array('adif' => 224, 'state' => '612', 'subdivision' => 'Joutsa'),
				array('adif' => 224, 'state' => '613', 'subdivision' => 'Jurva'),
				array('adif' => 224, 'state' => '614', 'subdivision' => 'Jyväskylä'),
				array('adif' => 224, 'state' => '615', 'subdivision' => 'Jyväskylän mlk'),
				array('adif' => 224, 'state' => '616', 'subdivision' => 'Jämsä'),
				array('adif' => 224, 'state' => '617', 'subdivision' => 'Jämsänkoski'),
				array('adif' => 224, 'state' => '619', 'subdivision' => 'Kannonkoski'),
				array('adif' => 224, 'state' => '620', 'subdivision' => 'Kannus'),
				array('adif' => 224, 'state' => '621', 'subdivision' => 'Karijoki'),
				array('adif' => 224, 'state' => '622', 'subdivision' => 'Karstula'),
				array('adif' => 224, 'state' => '623', 'subdivision' => 'Kaskinen'),
				array('adif' => 224, 'state' => '624', 'subdivision' => 'Kauhajoki'),
				array('adif' => 224, 'state' => '625', 'subdivision' => 'Kauhava'),
				array('adif' => 224, 'state' => '626', 'subdivision' => 'Kaustinen'),
				array('adif' => 224, 'state' => '627', 'subdivision' => 'Keuruu'),
				array('adif' => 224, 'state' => '628', 'subdivision' => 'Kinnula'),
				array('adif' => 224, 'state' => '629', 'subdivision' => 'Kivijärvi'),
				array('adif' => 224, 'state' => '630', 'subdivision' => 'Kokkola'),
				array('adif' => 224, 'state' => '632', 'subdivision' => 'Konnevesi'),
				array('adif' => 224, 'state' => '633', 'subdivision' => 'Korpilahti'),
				array('adif' => 224, 'state' => '634', 'subdivision' => 'Korsnäs'),
				array('adif' => 224, 'state' => '635', 'subdivision' => 'Kortesjärvi'),
				array('adif' => 224, 'state' => '636', 'subdivision' => 'Kristiinankaupunki'),
				array('adif' => 224, 'state' => '637', 'subdivision' => 'Kruunupyy'),
				array('adif' => 224, 'state' => '638', 'subdivision' => 'Kuhmoinen'),
				array('adif' => 224, 'state' => '639', 'subdivision' => 'Kuortane'),
				array('adif' => 224, 'state' => '640', 'subdivision' => 'Kurikka'),
				array('adif' => 224, 'state' => '641', 'subdivision' => 'Kyyjärvi'),
				array('adif' => 224, 'state' => '642', 'subdivision' => 'Kälviä'),
				array('adif' => 224, 'state' => '643', 'subdivision' => 'Laihia'),
				array('adif' => 224, 'state' => '644', 'subdivision' => 'Lappajärvi'),
				array('adif' => 224, 'state' => '645', 'subdivision' => 'Lapua'),
				array('adif' => 224, 'state' => '646', 'subdivision' => 'Laukaa'),
				array('adif' => 224, 'state' => '647', 'subdivision' => 'Lehtimäki'),
				array('adif' => 224, 'state' => '648', 'subdivision' => 'Leivonmäki'),
				array('adif' => 224, 'state' => '649', 'subdivision' => 'Lestijärvi'),
				array('adif' => 224, 'state' => '650', 'subdivision' => 'Lohtaja'),
				array('adif' => 224, 'state' => '651', 'subdivision' => 'Luhanka'),
				array('adif' => 224, 'state' => '652', 'subdivision' => 'Luoto'),
				array('adif' => 224, 'state' => '653', 'subdivision' => 'Maalahti'),
				array('adif' => 224, 'state' => '654', 'subdivision' => 'Maksamaa'),
				array('adif' => 224, 'state' => '655', 'subdivision' => 'Multia'),
				array('adif' => 224, 'state' => '656', 'subdivision' => 'Mustasaari'),
				array('adif' => 224, 'state' => '657', 'subdivision' => 'Muurame'),
				array('adif' => 224, 'state' => '658', 'subdivision' => 'Nurmo'),
				array('adif' => 224, 'state' => '659', 'subdivision' => 'Närpiö'),
				array('adif' => 224, 'state' => '660', 'subdivision' => 'Oravainen'),
				array('adif' => 224, 'state' => '661', 'subdivision' => 'Perho'),
				array('adif' => 224, 'state' => '662', 'subdivision' => 'Peräseinäjoki'),
				array('adif' => 224, 'state' => '663', 'subdivision' => 'Petäjävesi'),
				array('adif' => 224, 'state' => '664', 'subdivision' => 'Pietarsaari'),
				array('adif' => 224, 'state' => '665', 'subdivision' => 'Pedersöre'),
				array('adif' => 224, 'state' => '666', 'subdivision' => 'Pihtipudas'),
				array('adif' => 224, 'state' => '668', 'subdivision' => 'Pylkönmäki'),
				array('adif' => 224, 'state' => '669', 'subdivision' => 'Saarijärvi'),
				array('adif' => 224, 'state' => '670', 'subdivision' => 'Seinäjoki'),
				array('adif' => 224, 'state' => '671', 'subdivision' => 'Soini'),
				array('adif' => 224, 'state' => '672', 'subdivision' => 'Sumiainen'),
				array('adif' => 224, 'state' => '673', 'subdivision' => 'Suolahti'),
				array('adif' => 224, 'state' => '675', 'subdivision' => 'Teuva'),
				array('adif' => 224, 'state' => '676', 'subdivision' => 'Toholampi'),
				array('adif' => 224, 'state' => '677', 'subdivision' => 'Toivakka'),
				array('adif' => 224, 'state' => '678', 'subdivision' => 'Töysä'),
				array('adif' => 224, 'state' => '679', 'subdivision' => 'Ullava'),
				array('adif' => 224, 'state' => '680', 'subdivision' => 'Uurainen'),
				array('adif' => 224, 'state' => '681', 'subdivision' => 'Uusikaarlepyy'),
				array('adif' => 224, 'state' => '682', 'subdivision' => 'Vaasa'),
				array('adif' => 224, 'state' => '683', 'subdivision' => 'Veteli'),
				array('adif' => 224, 'state' => '684', 'subdivision' => 'Viitasaari'),
				array('adif' => 224, 'state' => '685', 'subdivision' => 'Vimpeli'),
				array('adif' => 224, 'state' => '686', 'subdivision' => 'Vähäkyrö'),
				array('adif' => 224, 'state' => '687', 'subdivision' => 'Vöyri'),
				array('adif' => 224, 'state' => '688', 'subdivision' => 'Ylihärmä'),
				array('adif' => 224, 'state' => '689', 'subdivision' => 'Ylistaro'),
				array('adif' => 224, 'state' => '690', 'subdivision' => 'Ähtäri'),
				array('adif' => 224, 'state' => '692', 'subdivision' => 'Äänekoski'),
				array('adif' => 224, 'state' => '701', 'subdivision' => 'Eno'),
				array('adif' => 224, 'state' => '702', 'subdivision' => 'Iisalmi'),
				array('adif' => 224, 'state' => '703', 'subdivision' => 'Ilomantsi'),
				array('adif' => 224, 'state' => '704', 'subdivision' => 'Joensuu'),
				array('adif' => 224, 'state' => '705', 'subdivision' => 'Juankoski'),
				array('adif' => 224, 'state' => '706', 'subdivision' => 'Juuka'),
				array('adif' => 224, 'state' => '707', 'subdivision' => 'Kaavi'),
				array('adif' => 224, 'state' => '708', 'subdivision' => 'Karttula'),
				array('adif' => 224, 'state' => '709', 'subdivision' => 'Keitele'),
				array('adif' => 224, 'state' => '710', 'subdivision' => 'Kesälahti'),
				array('adif' => 224, 'state' => '711', 'subdivision' => 'Kiihtelysvaara'),
				array('adif' => 224, 'state' => '712', 'subdivision' => 'Kitee'),
				array('adif' => 224, 'state' => '713', 'subdivision' => 'Kiuruvesi'),
				array('adif' => 224, 'state' => '714', 'subdivision' => 'Kontiolahti'),
				array('adif' => 224, 'state' => '715', 'subdivision' => 'Kuopio'),
				array('adif' => 224, 'state' => '716', 'subdivision' => 'Lapinlahti'),
				array('adif' => 224, 'state' => '717', 'subdivision' => 'Leppävirta'),
				array('adif' => 224, 'state' => '718', 'subdivision' => 'Lieksa'),
				array('adif' => 224, 'state' => '719', 'subdivision' => 'Liperi'),
				array('adif' => 224, 'state' => '720', 'subdivision' => 'Maaninka'),
				array('adif' => 224, 'state' => '721', 'subdivision' => 'Nilsiä'),
				array('adif' => 224, 'state' => '722', 'subdivision' => 'Nurmes'),
				array('adif' => 224, 'state' => '723', 'subdivision' => 'Outokumpu'),
				array('adif' => 224, 'state' => '724', 'subdivision' => 'Pielavesi'),
				array('adif' => 224, 'state' => '725', 'subdivision' => 'Polvijärvi'),
				array('adif' => 224, 'state' => '726', 'subdivision' => 'Pyhäselkä'),
				array('adif' => 224, 'state' => '727', 'subdivision' => 'Rautalampi'),
				array('adif' => 224, 'state' => '728', 'subdivision' => 'Rautavaara'),
				array('adif' => 224, 'state' => '729', 'subdivision' => 'Rääkkylä'),
				array('adif' => 224, 'state' => '730', 'subdivision' => 'Siilinjärvi'),
				array('adif' => 224, 'state' => '731', 'subdivision' => 'Sonkajärvi'),
				array('adif' => 224, 'state' => '732', 'subdivision' => 'Suonenjoki'),
				array('adif' => 224, 'state' => '733', 'subdivision' => 'Tervo'),
				array('adif' => 224, 'state' => '734', 'subdivision' => 'Tohmajärvi'),
				array('adif' => 224, 'state' => '735', 'subdivision' => 'Tuupovaara'),
				array('adif' => 224, 'state' => '736', 'subdivision' => 'Tuusniemi'),
				array('adif' => 224, 'state' => '737', 'subdivision' => 'Valtimo'),
				array('adif' => 224, 'state' => '738', 'subdivision' => 'Varkaus'),
				array('adif' => 224, 'state' => '739', 'subdivision' => 'Varpaisjärvi'),
				array('adif' => 224, 'state' => '740', 'subdivision' => 'Vehmersalmi'),
				array('adif' => 224, 'state' => '741', 'subdivision' => 'Vesanto'),
				array('adif' => 224, 'state' => '742', 'subdivision' => 'Vieremä'),
				array('adif' => 224, 'state' => '743', 'subdivision' => 'Värtsilä'),
				array('adif' => 224, 'state' => '801', 'subdivision' => 'Alavieska'),
				array('adif' => 224, 'state' => '802', 'subdivision' => 'Haapajärvi'),
				array('adif' => 224, 'state' => '803', 'subdivision' => 'Haapavesi'),
				array('adif' => 224, 'state' => '804', 'subdivision' => 'Hailuoto'),
				array('adif' => 224, 'state' => '805', 'subdivision' => 'Haukipudas'),
				array('adif' => 224, 'state' => '806', 'subdivision' => 'Hyrynsalmi'),
				array('adif' => 224, 'state' => '807', 'subdivision' => 'Ii'),
				array('adif' => 224, 'state' => '808', 'subdivision' => 'Kajaani'),
				array('adif' => 224, 'state' => '810', 'subdivision' => 'Kalajoki'),
				array('adif' => 224, 'state' => '811', 'subdivision' => 'Kempele'),
				array('adif' => 224, 'state' => '812', 'subdivision' => 'Kestilä'),
				array('adif' => 224, 'state' => '813', 'subdivision' => 'Kiiminki'),
				array('adif' => 224, 'state' => '814', 'subdivision' => 'Kuhmo'),
				array('adif' => 224, 'state' => '815', 'subdivision' => 'Kuivaniemi'),
				array('adif' => 224, 'state' => '816', 'subdivision' => 'Kuusamo'),
				array('adif' => 224, 'state' => '817', 'subdivision' => 'Kärsämäki'),
				array('adif' => 224, 'state' => '818', 'subdivision' => 'Liminka'),
				array('adif' => 224, 'state' => '819', 'subdivision' => 'Lumijoki'),
				array('adif' => 224, 'state' => '820', 'subdivision' => 'Merijärvi'),
				array('adif' => 224, 'state' => '821', 'subdivision' => 'Muhos'),
				array('adif' => 224, 'state' => '822', 'subdivision' => 'Nivala'),
				array('adif' => 224, 'state' => '823', 'subdivision' => 'Oulainen'),
				array('adif' => 224, 'state' => '824', 'subdivision' => 'Oulu'),
				array('adif' => 224, 'state' => '825', 'subdivision' => 'Oulunsalo'),
				array('adif' => 224, 'state' => '826', 'subdivision' => 'Paltamo'),
				array('adif' => 224, 'state' => '827', 'subdivision' => 'Pattijoki'),
				array('adif' => 224, 'state' => '828', 'subdivision' => 'Piippola'),
				array('adif' => 224, 'state' => '829', 'subdivision' => 'Pudasjärvi'),
				array('adif' => 224, 'state' => '830', 'subdivision' => 'Pulkkila'),
				array('adif' => 224, 'state' => '831', 'subdivision' => 'Puolanka'),
				array('adif' => 224, 'state' => '832', 'subdivision' => 'Pyhäjoki'),
				array('adif' => 224, 'state' => '833', 'subdivision' => 'Pyhäjärvi'),
				array('adif' => 224, 'state' => '834', 'subdivision' => 'Pyhäntä'),
				array('adif' => 224, 'state' => '835', 'subdivision' => 'Raahe'),
				array('adif' => 224, 'state' => '836', 'subdivision' => 'Rantsila'),
				array('adif' => 224, 'state' => '837', 'subdivision' => 'Reisjärvi'),
				array('adif' => 224, 'state' => '838', 'subdivision' => 'Ristijärvi'),
				array('adif' => 224, 'state' => '839', 'subdivision' => 'Ruukki'),
				array('adif' => 224, 'state' => '840', 'subdivision' => 'Sievi'),
				array('adif' => 224, 'state' => '841', 'subdivision' => 'Siikajoki'),
				array('adif' => 224, 'state' => '842', 'subdivision' => 'Sotkamo'),
				array('adif' => 224, 'state' => '843', 'subdivision' => 'Suomussalmi'),
				array('adif' => 224, 'state' => '844', 'subdivision' => 'Taivalkoski'),
				array('adif' => 224, 'state' => '846', 'subdivision' => 'Tyrnävä'),
				array('adif' => 224, 'state' => '847', 'subdivision' => 'Utajärvi'),
				array('adif' => 224, 'state' => '848', 'subdivision' => 'Vaala'),
				array('adif' => 224, 'state' => '849', 'subdivision' => 'Vihanti'),
				array('adif' => 224, 'state' => '850', 'subdivision' => 'Vuolijoki'),
				array('adif' => 224, 'state' => '851', 'subdivision' => 'Yli-Ii'),
				array('adif' => 224, 'state' => '852', 'subdivision' => 'Ylikiiminki'),
				array('adif' => 224, 'state' => '853', 'subdivision' => 'Ylivieska'),
				array('adif' => 224, 'state' => '901', 'subdivision' => 'Enontekiö'),
				array('adif' => 224, 'state' => '902', 'subdivision' => 'Inari'),
				array('adif' => 224, 'state' => '903', 'subdivision' => 'Kemi'),
				array('adif' => 224, 'state' => '904', 'subdivision' => 'Keminmaa'),
				array('adif' => 224, 'state' => '905', 'subdivision' => 'Kemijärvi'),
				array('adif' => 224, 'state' => '907', 'subdivision' => 'Kittilä'),
				array('adif' => 224, 'state' => '908', 'subdivision' => 'Kolari'),
				array('adif' => 224, 'state' => '909', 'subdivision' => 'Muonio'),
				array('adif' => 224, 'state' => '910', 'subdivision' => 'Pelkosenniemi'),
				array('adif' => 224, 'state' => '911', 'subdivision' => 'Pello'),
				array('adif' => 224, 'state' => '912', 'subdivision' => 'Posio'),
				array('adif' => 224, 'state' => '913', 'subdivision' => 'Ranua'),
				array('adif' => 224, 'state' => '914', 'subdivision' => 'Rovaniemi'),
				array('adif' => 224, 'state' => '915', 'subdivision' => 'Rovaniemen mlk'),
				array('adif' => 224, 'state' => '916', 'subdivision' => 'Salla'),
				array('adif' => 224, 'state' => '917', 'subdivision' => 'Savukoski'),
				array('adif' => 224, 'state' => '918', 'subdivision' => 'Simo'),
				array('adif' => 224, 'state' => '919', 'subdivision' => 'Sodankylä'),
				array('adif' => 224, 'state' => '920', 'subdivision' => 'Tervola'),
				array('adif' => 224, 'state' => '921', 'subdivision' => 'Tornio'),
				array('adif' => 224, 'state' => '922', 'subdivision' => 'Utsjoki'),
				array('adif' => 224, 'state' => '923', 'subdivision' => 'Ylitornio'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 224, 'state' => 'CA', 'subdivision' => 'Cagliari'),
				array('adif' => 224, 'state' => 'CI', 'subdivision' => 'Carbonia-Iglesias'),
				array('adif' => 224, 'state' => 'MD', 'subdivision' => 'Medio Campidano'),
				array('adif' => 224, 'state' => 'NU', 'subdivision' => 'Nuoro'),
				array('adif' => 224, 'state' => 'OG', 'subdivision' => 'Ogliastra'),
				array('adif' => 224, 'state' => 'OR', 'subdivision' => 'Oristano'),
				array('adif' => 224, 'state' => 'OT', 'subdivision' => 'Olbia-Tempio'),
				array('adif' => 224, 'state' => 'SS', 'subdivision' => 'Sassari'),
				array('adif' => 224, 'state' => 'VS', 'subdivision' => 'MedioCampidano'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 227, 'state' => '01', 'subdivision' => 'Ain'),
				array('adif' => 227, 'state' => '02', 'subdivision' => 'Aisne'),
				array('adif' => 227, 'state' => '03', 'subdivision' => 'Allier'),
				array('adif' => 227, 'state' => '04', 'subdivision' => 'Alpes-de-Haute-Provence'),
				array('adif' => 227, 'state' => '05', 'subdivision' => 'Hautes-Alpes'),
				array('adif' => 227, 'state' => '06', 'subdivision' => 'Alpes-Maritimes'),
				array('adif' => 227, 'state' => '07', 'subdivision' => 'Ardèche'),
				array('adif' => 227, 'state' => '08', 'subdivision' => 'Ardennes'),
				array('adif' => 227, 'state' => '09', 'subdivision' => 'Ariège'),
				array('adif' => 227, 'state' => '10', 'subdivision' => 'Aube'),
				array('adif' => 227, 'state' => '11', 'subdivision' => 'Aude'),
				array('adif' => 227, 'state' => '12', 'subdivision' => 'Aveyron'),
				array('adif' => 227, 'state' => '13', 'subdivision' => 'Bouches-du-Rhone'),
				array('adif' => 227, 'state' => '14', 'subdivision' => 'Calvados'),
				array('adif' => 227, 'state' => '15', 'subdivision' => 'Cantal'),
				array('adif' => 227, 'state' => '16', 'subdivision' => 'Charente'),
				array('adif' => 227, 'state' => '17', 'subdivision' => 'Charente-Maritime'),
				array('adif' => 227, 'state' => '18', 'subdivision' => 'Cher'),
				array('adif' => 227, 'state' => '19', 'subdivision' => 'Corrèze'),
				array('adif' => 227, 'state' => '21', 'subdivision' => 'Cote-d\'Or'),
				array('adif' => 227, 'state' => '22', 'subdivision' => 'Cotes-d\'Armor'),
				array('adif' => 227, 'state' => '23', 'subdivision' => 'Creuse'),
				array('adif' => 227, 'state' => '24', 'subdivision' => 'Dordogne'),
				array('adif' => 227, 'state' => '25', 'subdivision' => 'Doubs'),
				array('adif' => 227, 'state' => '26', 'subdivision' => 'Drôme'),
				array('adif' => 227, 'state' => '27', 'subdivision' => 'Eure'),
				array('adif' => 227, 'state' => '28', 'subdivision' => 'Eure-et-Loir'),
				array('adif' => 227, 'state' => '29', 'subdivision' => 'Finistère'),
				array('adif' => 227, 'state' => '30', 'subdivision' => 'Gard'),
				array('adif' => 227, 'state' => '31', 'subdivision' => 'Haute-Garonne'),
				array('adif' => 227, 'state' => '32', 'subdivision' => 'Gere'),
				array('adif' => 227, 'state' => '33', 'subdivision' => 'Gironde'),
				array('adif' => 227, 'state' => '34', 'subdivision' => 'Hérault'),
				array('adif' => 227, 'state' => '35', 'subdivision' => 'Ille-et-Vilaine'),
				array('adif' => 227, 'state' => '36', 'subdivision' => 'Indre'),
				array('adif' => 227, 'state' => '37', 'subdivision' => 'Indre-et-Loire'),
				array('adif' => 227, 'state' => '38', 'subdivision' => 'Isère'),
				array('adif' => 227, 'state' => '39', 'subdivision' => 'Jura'),
				array('adif' => 227, 'state' => '40', 'subdivision' => 'Landes'),
				array('adif' => 227, 'state' => '41', 'subdivision' => 'Loir-et-Cher'),
				array('adif' => 227, 'state' => '42', 'subdivision' => 'Loire'),
				array('adif' => 227, 'state' => '43', 'subdivision' => 'Haute-Loire'),
				array('adif' => 227, 'state' => '44', 'subdivision' => 'Loire-Atlantique'),
				array('adif' => 227, 'state' => '45', 'subdivision' => 'Loiret'),
				array('adif' => 227, 'state' => '46', 'subdivision' => 'Lot'),
				array('adif' => 227, 'state' => '47', 'subdivision' => 'Lot-et-Garonne'),
				array('adif' => 227, 'state' => '48', 'subdivision' => 'Lozère'),
				array('adif' => 227, 'state' => '49', 'subdivision' => 'Maine-et-Loire'),
				array('adif' => 227, 'state' => '50', 'subdivision' => 'Manche'),
				array('adif' => 227, 'state' => '51', 'subdivision' => 'Marne'),
				array('adif' => 227, 'state' => '52', 'subdivision' => 'Haute-Marne'),
				array('adif' => 227, 'state' => '53', 'subdivision' => 'Mayenne'),
				array('adif' => 227, 'state' => '54', 'subdivision' => 'Meurthe-et-Moselle'),
				array('adif' => 227, 'state' => '55', 'subdivision' => 'Meuse'),
				array('adif' => 227, 'state' => '56', 'subdivision' => 'Morbihan'),
				array('adif' => 227, 'state' => '57', 'subdivision' => 'Moselle'),
				array('adif' => 227, 'state' => '58', 'subdivision' => 'Niëvre'),
				array('adif' => 227, 'state' => '59', 'subdivision' => 'Nord'),
				array('adif' => 227, 'state' => '60', 'subdivision' => 'Oise'),
				array('adif' => 227, 'state' => '61', 'subdivision' => 'Orne'),
				array('adif' => 227, 'state' => '62', 'subdivision' => 'Pas-de-Calais'),
				array('adif' => 227, 'state' => '63', 'subdivision' => 'Puy-de-Dôme'),
				array('adif' => 227, 'state' => '64', 'subdivision' => 'Pyrénées-Atlantiques'),
				array('adif' => 227, 'state' => '65', 'subdivision' => 'Hautea-Pyrénées'),
				array('adif' => 227, 'state' => '66', 'subdivision' => 'Pyrénées-Orientales'),
				array('adif' => 227, 'state' => '67', 'subdivision' => 'Bas-Rhin'),
				array('adif' => 227, 'state' => '68', 'subdivision' => 'Haut-Rhin'),
				array('adif' => 227, 'state' => '69', 'subdivision' => 'Rhône'),
				array('adif' => 227, 'state' => '70', 'subdivision' => 'Haute-Saône'),
				array('adif' => 227, 'state' => '71', 'subdivision' => 'Saône-et-Loire'),
				array('adif' => 227, 'state' => '72', 'subdivision' => 'Sarthe'),
				array('adif' => 227, 'state' => '73', 'subdivision' => 'Savoie'),
				array('adif' => 227, 'state' => '74', 'subdivision' => 'Haute-Savoie'),
				array('adif' => 227, 'state' => '75', 'subdivision' => 'Paris'),
				array('adif' => 227, 'state' => '76', 'subdivision' => 'Seine-Maritime'),
				array('adif' => 227, 'state' => '77', 'subdivision' => 'Seine-et-Marne'),
				array('adif' => 227, 'state' => '78', 'subdivision' => 'Yvelines'),
				array('adif' => 227, 'state' => '79', 'subdivision' => 'Deux-Sèvres'),
				array('adif' => 227, 'state' => '80', 'subdivision' => 'Somme'),
				array('adif' => 227, 'state' => '81', 'subdivision' => 'Tarn'),
				array('adif' => 227, 'state' => '82', 'subdivision' => 'Tarn-et-Garonne'),
				array('adif' => 227, 'state' => '83', 'subdivision' => 'Var'),
				array('adif' => 227, 'state' => '84', 'subdivision' => 'Vaucluse'),
				array('adif' => 227, 'state' => '85', 'subdivision' => 'Vendée'),
				array('adif' => 227, 'state' => '86', 'subdivision' => 'Vienne'),
				array('adif' => 227, 'state' => '87', 'subdivision' => 'Haute-Vienne'),
				array('adif' => 227, 'state' => '88', 'subdivision' => 'Vosges'),
				array('adif' => 227, 'state' => '89', 'subdivision' => 'Yonne'),
				array('adif' => 227, 'state' => '90', 'subdivision' => 'Territoire de Belfort'),
				array('adif' => 227, 'state' => '91', 'subdivision' => 'Essonne'),
				array('adif' => 227, 'state' => '92', 'subdivision' => 'Hauts-de-Selne'),
				array('adif' => 227, 'state' => '93', 'subdivision' => 'Seine-Saint-Denis'),
				array('adif' => 227, 'state' => '94', 'subdivision' => 'Val-de-Marne'),
				array('adif' => 227, 'state' => '95', 'subdivision' => 'Val-d\'Oise'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 230, 'state' => 'BB', 'subdivision' => 'Brandenburg'),
				array('adif' => 230, 'state' => 'BE', 'subdivision' => 'Berlin'),
				array('adif' => 230, 'state' => 'BW', 'subdivision' => 'Baden-Württemberg'),
				array('adif' => 230, 'state' => 'BY', 'subdivision' => 'Freistaat Bayern'),
				array('adif' => 230, 'state' => 'HB', 'subdivision' => 'Freie Hansestadt Bremen'),
				array('adif' => 230, 'state' => 'HE', 'subdivision' => 'Hessen'),
				array('adif' => 230, 'state' => 'HH', 'subdivision' => 'Freie und Hansestadt Hamburg'),
				array('adif' => 230, 'state' => 'MV', 'subdivision' => 'Mecklenburg-Vorpommern'),
				array('adif' => 230, 'state' => 'NI', 'subdivision' => 'Niedersachsen'),
				array('adif' => 230, 'state' => 'NW', 'subdivision' => 'Nordrhein-Westfalen'),
				array('adif' => 230, 'state' => 'RP', 'subdivision' => 'Rheinland-Pfalz'),
				array('adif' => 230, 'state' => 'SL', 'subdivision' => 'Saarland'),
				array('adif' => 230, 'state' => 'SH', 'subdivision' => 'Schleswig-Holstein'),
				array('adif' => 230, 'state' => 'SN', 'subdivision' => 'Freistaat Sachsen'),
				array('adif' => 230, 'state' => 'ST', 'subdivision' => 'Sachsen-Anhalt'),
				array('adif' => 230, 'state' => 'TH', 'subdivision' => 'Freistaat Thüringen'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

			$data = array(
				array('adif' => 339, 'state' => '01', 'subdivision' => 'Hokkaido'),
				array('adif' => 339, 'state' => '02', 'subdivision' => 'Aomori'),
				array('adif' => 339, 'state' => '03', 'subdivision' => 'Iwate'),
				array('adif' => 339, 'state' => '04', 'subdivision' => 'Akita'),
				array('adif' => 339, 'state' => '05', 'subdivision' => 'Yamagata'),
				array('adif' => 339, 'state' => '06', 'subdivision' => 'Miyagi'),
				array('adif' => 339, 'state' => '07', 'subdivision' => 'Fukushima'),
				array('adif' => 339, 'state' => '08', 'subdivision' => 'Niigata'),
				array('adif' => 339, 'state' => '09', 'subdivision' => 'Nagano'),
				array('adif' => 339, 'state' => '10', 'subdivision' => 'Tokyo'),
				array('adif' => 339, 'state' => '11', 'subdivision' => 'Kanagawa'),
				array('adif' => 339, 'state' => '12', 'subdivision' => 'Chiba'),
				array('adif' => 339, 'state' => '13', 'subdivision' => 'Saitama'),
				array('adif' => 339, 'state' => '14', 'subdivision' => 'Ibaraki'),
				array('adif' => 339, 'state' => '15', 'subdivision' => 'Tochigi'),
				array('adif' => 339, 'state' => '16', 'subdivision' => 'Gunma'),
				array('adif' => 339, 'state' => '17', 'subdivision' => 'Yamanashi'),
				array('adif' => 339, 'state' => '18', 'subdivision' => 'Shizuoka'),
				array('adif' => 339, 'state' => '19', 'subdivision' => 'Gifu'),
				array('adif' => 339, 'state' => '20', 'subdivision' => 'Aichi'),
				array('adif' => 339, 'state' => '21', 'subdivision' => 'Mie'),
				array('adif' => 339, 'state' => '22', 'subdivision' => 'Kyoto'),
				array('adif' => 339, 'state' => '23', 'subdivision' => 'Shiga'),
				array('adif' => 339, 'state' => '24', 'subdivision' => 'Nara'),
				array('adif' => 339, 'state' => '25', 'subdivision' => 'Osaka'),
				array('adif' => 339, 'state' => '26', 'subdivision' => 'Wakayama'),
				array('adif' => 339, 'state' => '27', 'subdivision' => 'Hyogo'),
				array('adif' => 339, 'state' => '28', 'subdivision' => 'Toyama'),
				array('adif' => 339, 'state' => '29', 'subdivision' => 'Fukui'),
				array('adif' => 339, 'state' => '30', 'subdivision' => 'Ishikawa'),
				array('adif' => 339, 'state' => '31', 'subdivision' => 'Okayama'),
				array('adif' => 339, 'state' => '32', 'subdivision' => 'Shimane'),
				array('adif' => 339, 'state' => '33', 'subdivision' => 'Yamaguchi'),
				array('adif' => 339, 'state' => '34', 'subdivision' => 'Tottori'),
				array('adif' => 339, 'state' => '35', 'subdivision' => 'Hiroshima'),
				array('adif' => 339, 'state' => '36', 'subdivision' => 'Kagawa'),
				array('adif' => 339, 'state' => '37', 'subdivision' => 'Tokushima'),
				array('adif' => 339, 'state' => '38', 'subdivision' => 'Ehime'),
				array('adif' => 339, 'state' => '39', 'subdivision' => 'Kochi'),
				array('adif' => 339, 'state' => '40', 'subdivision' => 'Fukuoka'),
				array('adif' => 339, 'state' => '41', 'subdivision' => 'Saga'),
				array('adif' => 339, 'state' => '42', 'subdivision' => 'Nagasaki'),
				array('adif' => 339, 'state' => '43', 'subdivision' => 'Kumamoto'),
				array('adif' => 339, 'state' => '44', 'subdivision' => 'Oita'),
				array('adif' => 339, 'state' => '45', 'subdivision' => 'Miyazaki'),
				array('adif' => 339, 'state' => '46', 'subdivision' => 'Kagoshima'),
				array('adif' => 339, 'state' => '47', 'subdivision' => 'Okinawa'),
			);
			$this->db->insert_batch('primary_subdivisions', $data);

		}
	}

	public function down()
	{
		$this->dbforge->drop_table('primary_subdivisions', 'TRUE');
	}
}
