SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for api
-- ----------------------------
DROP TABLE IF EXISTS `api`;
CREATE TABLE `api` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `key` varchar(255) NOT NULL,
  `rights` varchar(10) NOT NULL,
  `status` varchar(10) NOT NULL,
  `last_change` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
-- Records of api
-- ----------------------------

-- ----------------------------
-- Table structure for cat
-- ----------------------------
DROP TABLE IF EXISTS `cat`;
CREATE TABLE `cat` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `radio` varchar(250) NOT NULL,
  `frequency` bigint(13) NOT NULL,
  `mode` varchar(10) NOT NULL,
  `downlink_freq` bigint(13) DEFAULT NULL,
  `uplink_freq` bigint(13) DEFAULT NULL,
  `downlink_mode` varchar(255) DEFAULT NULL,
  `uplink_mode` varchar(255) DEFAULT NULL,
  `sat_name` varchar(255) DEFAULT NULL,
  `timestamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
-- Records of cat
-- ----------------------------

-- ----------------------------
-- Table structure for config
-- ----------------------------
DROP TABLE IF EXISTS `config`;
CREATE TABLE `config` (
  `id` int(9) NOT NULL AUTO_INCREMENT,
  `lotw_download_url` varchar(255) DEFAULT NULL,
  `lotw_upload_url` varchar(255) DEFAULT NULL,
  `lotw_rcvd_mark` varchar(1) DEFAULT NULL,
  `lotw_login_url` varchar(244) DEFAULT NULL,
  `eqsl_download_url` varchar(244) DEFAULT NULL,
  `eqsl_rcvd_mark` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
-- Records of config
-- ----------------------------
INSERT INTO `config` VALUES ('1', 'https://lotw.arrl.org/lotwuser/lotwreport.adi', 'https://lotw.arrl.org/lotwuser/upload', 'Y', 'https://lotw.arrl.org/lotwuser/default', 'http://www.eqsl.cc/qslcard/DownloadInBox.cfm', 'Y');

-- ----------------------------
-- Table structure for migrations
-- ----------------------------
DROP TABLE IF EXISTS `migrations`;
CREATE TABLE `migrations` (
  `version` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of migrations
-- ----------------------------
INSERT INTO `migrations` VALUES ('15');

-- ----------------------------
-- Table structure for notes
-- ----------------------------
DROP TABLE IF EXISTS `notes`;
CREATE TABLE `notes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cat` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL,
  `note` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
-- Records of notes
-- ----------------------------

-- ----------------------------
-- Table structure for station_profile
-- ----------------------------
CREATE TABLE `station_profile` (
  `station_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `station_profile_name` varchar(200) NOT NULL,
  `station_gridsquare` varchar(100) NOT NULL,
  `station_city` varchar(100) NOT NULL,
  `station_iota` varchar(100) NOT NULL,
  `station_sota` varchar(10) NOT NULL,
  `station_callsign` varchar(50) DEFAULT NULL,
  `station_power` smallint(6) DEFAULT NULL,
  `station_dxcc` int(10) DEFAULT NULL,
  `station_cnty` varchar(200) DEFAULT NULL,
  `station_cq` int(5) DEFAULT NULL,
  `station_itu` int(5) DEFAULT NULL,
  `station_active` tinyint(1) DEFAULT NULL,
  `eqslqthnickname` varchar(255) DEFAULT NULL,
  `state` varchar(4) DEFAULT NULL,
  `qrzapikey` varchar(20) DEFAULT NULL,
  `county` varchar(255) DEFAULT NULL,
  `station_sig` varchar(50) DEFAULT NULL,
  `station_sig_info` varchar(50) DEFAULT NULL,
  `qrzrealtime` tinyint(1) DEFAULT 0,
  `user_id` int(10) unsigned NOT NULL,
  `station_wwff` varchar(50) DEFAULT NULL,
  `station_pota` varchar(50) DEFAULT NULL,
  `oqrs` int(11) DEFAULT 0,
  `oqrs_text` text DEFAULT NULL,
  `oqrs_email` int(11) DEFAULT 0,
  `webadifapikey` varchar(50) DEFAULT NULL,
  `webadifapiurl` varchar(256) DEFAULT NULL,
  `webadifrealtime` tinyint(1) DEFAULT 0,
  `clublogrealtime` tinyint(4) NOT NULL DEFAULT 0,
  `hrdlogrealtime` tinyint(1) DEFAULT NULL,
  `hrdlog_code` varchar(20) DEFAULT NULL,
  `hrdlog_username` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`station_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ----------------------------
-- Table structure for station_logbooks
-- ----------------------------
DROP TABLE IF EXISTS `station_logbooks`;
CREATE TABLE `station_logbooks` (
  `logbook_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `logbook_name` varchar(191) DEFAULT NULL,
  `modified` timestamp NULL DEFAULT NULL,
  `public_slug` varchar(191) DEFAULT NULL,
  `public_search` int(11) DEFAULT 0,
  PRIMARY KEY (`logbook_id`,`user_id`),
  UNIQUE KEY `logbook_id` (`logbook_id`),
  UNIQUE KEY `public_slug` (`public_slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
-- Table structure for station_logbooks_relationship
-- ----------------------------
DROP TABLE IF EXISTS `station_logbooks_relationship`;
CREATE TABLE `station_logbooks_relationship` (
  `logbook_relation_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `station_logbook_id` int(10) unsigned NOT NULL,
  `station_location_id` int(10) unsigned NOT NULL,
  `modified` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`logbook_relation_id`,`station_logbook_id`,`station_location_id`),
  UNIQUE KEY `logbook_relation_id` (`logbook_relation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
-- Table structure for TABLE_HRD_CONTACTS_V01
-- ----------------------------
DROP TABLE IF EXISTS `TABLE_HRD_CONTACTS_V01`;
CREATE TABLE `TABLE_HRD_CONTACTS_V01` (
  `COL_PRIMARY_KEY` int(11) NOT NULL AUTO_INCREMENT,
  `COL_ADDRESS` varchar(255) DEFAULT NULL,
  `COL_AGE` int(11) DEFAULT NULL,
  `COL_A_INDEX` double DEFAULT NULL,
  `COL_ANT_AZ` double DEFAULT NULL,
  `COL_ANT_EL` double DEFAULT NULL,
  `COL_ANT_PATH` varchar(2) DEFAULT NULL,
  `COL_ARRL_SECT` varchar(10) DEFAULT NULL,
  `COL_BAND` varchar(10) DEFAULT NULL,
  `COL_BAND_RX` varchar(10) DEFAULT NULL,
  `COL_BIOGRAPHY` longtext DEFAULT NULL,
  `COL_CALL` varchar(32) DEFAULT NULL,
  `COL_CHECK` varchar(8) DEFAULT NULL,
  `COL_CLASS` varchar(8) DEFAULT NULL,
  `COL_CNTY` varchar(32) DEFAULT NULL,
  `COL_COMMENT` longtext DEFAULT NULL,
  `COL_CONT` varchar(6) DEFAULT NULL,
  `COL_CONTACTED_OP` varchar(32) DEFAULT NULL,
  `COL_CONTEST_ID` varchar(32) DEFAULT NULL,
  `COL_COUNTRY` varchar(64) DEFAULT NULL,
  `COL_CQZ` int(11) DEFAULT NULL,
  `COL_DISTANCE` double DEFAULT NULL,
  `COL_DXCC` varchar(6) DEFAULT NULL,
  `COL_EMAIL` varchar(32) DEFAULT NULL,
  `COL_EQ_CALL` varchar(32) DEFAULT NULL,
  `COL_EQSL_QSLRDATE` datetime DEFAULT NULL,
  `COL_EQSL_QSLSDATE` datetime DEFAULT NULL,
  `COL_EQSL_QSL_RCVD` varchar(2) DEFAULT NULL,
  `COL_EQSL_QSL_SENT` varchar(2) DEFAULT NULL,
  `COL_EQSL_STATUS` varchar(255) DEFAULT NULL,
  `COL_FORCE_INIT` int(11) DEFAULT NULL,
  `COL_FREQ` bigint(13) DEFAULT NULL,
  `COL_FREQ_RX` bigint(13) DEFAULT NULL,
  `COL_GRIDSQUARE` varchar(12) DEFAULT NULL,
  `COL_HEADING` double DEFAULT NULL,
  `COL_IOTA` varchar(10) DEFAULT NULL,
  `COL_ITUZ` int(11) DEFAULT NULL,
  `COL_K_INDEX` double DEFAULT NULL,
  `COL_LAT` double DEFAULT NULL,
  `COL_LON` double DEFAULT NULL,
  `COL_LOTW_QSLRDATE` datetime DEFAULT NULL,
  `COL_LOTW_QSLSDATE` datetime DEFAULT NULL,
  `COL_LOTW_QSL_RCVD` varchar(2) DEFAULT NULL,
  `COL_LOTW_QSL_SENT` varchar(2) DEFAULT NULL,
  `COL_LOTW_STATUS` varchar(255) DEFAULT NULL,
  `COL_MAX_BURSTS` int(11) DEFAULT NULL,
  `COL_MODE` varchar(10) DEFAULT NULL,
  `COL_MS_SHOWER` varchar(32) DEFAULT NULL,
  `COL_MY_CITY` varchar(32) DEFAULT NULL,
  `COL_MY_CNTY` varchar(32) DEFAULT NULL,
  `COL_MY_COUNTRY` varchar(64) DEFAULT NULL,
  `COL_MY_CQ_ZONE` int(11) DEFAULT NULL,
  `COL_MY_GRIDSQUARE` varchar(12) DEFAULT NULL,
  `COL_MY_IOTA` varchar(10) DEFAULT NULL,
  `COL_MY_ITU_ZONE` int(11) DEFAULT NULL,
  `COL_MY_LAT` double DEFAULT NULL,
  `COL_MY_LON` double DEFAULT NULL,
  `COL_MY_NAME` varchar(64) DEFAULT NULL,
  `COL_MY_POSTAL_CODE` varchar(24) DEFAULT NULL,
  `COL_MY_RIG` varchar(255) DEFAULT NULL,
  `COL_MY_SIG` varchar(32) DEFAULT NULL,
  `COL_MY_SIG_INFO` varchar(64) DEFAULT NULL,
  `COL_MY_STATE` varchar(32) DEFAULT NULL,
  `COL_MY_STREET` varchar(64) DEFAULT NULL,
  `COL_NAME` varchar(128) DEFAULT NULL,
  `COL_NOTES` longtext DEFAULT NULL,
  `COL_NR_BURSTS` int(11) DEFAULT NULL,
  `COL_NR_PINGS` int(11) DEFAULT NULL,
  `COL_OPERATOR` varchar(32) DEFAULT NULL,
  `COL_OWNER_CALLSIGN` varchar(32) DEFAULT NULL,
  `COL_PFX` varchar(32) DEFAULT NULL,
  `COL_PRECEDENCE` varchar(32) DEFAULT NULL,
  `COL_PROP_MODE` varchar(8) DEFAULT NULL,
  `COL_PUBLIC_KEY` varchar(255) DEFAULT NULL,
  `COL_QSLMSG` varchar(255) DEFAULT NULL,
  `COL_QSLRDATE` datetime DEFAULT NULL,
  `COL_QSLSDATE` datetime DEFAULT NULL,
  `COL_QSL_RCVD` varchar(2) DEFAULT NULL,
  `COL_QSL_RCVD_VIA` varchar(2) DEFAULT NULL,
  `COL_QSL_SENT` varchar(2) DEFAULT NULL,
  `COL_QSL_SENT_VIA` varchar(2) DEFAULT NULL,
  `COL_QSL_VIA` varchar(255) DEFAULT NULL,
  `COL_QSO_COMPLETE` varchar(6) DEFAULT NULL,
  `COL_QSO_RANDOM` int(11) DEFAULT NULL,
  `COL_QTH` varchar(64) DEFAULT NULL,
  `COL_RIG` varchar(255) DEFAULT NULL,
  `COL_RST_RCVD` varchar(32) DEFAULT NULL,
  `COL_RST_SENT` varchar(32) DEFAULT NULL,
  `COL_RX_PWR` double DEFAULT NULL,
  `COL_SAT_MODE` varchar(32) DEFAULT NULL,
  `COL_SAT_NAME` varchar(32) DEFAULT NULL,
  `COL_SFI` double DEFAULT NULL,
  `COL_SIG` varchar(32) DEFAULT NULL,
  `COL_SIG_INFO` varchar(64) DEFAULT NULL,
  `COL_SRX` int(11) DEFAULT NULL,
  `COL_SRX_STRING` varchar(32) DEFAULT NULL,
  `COL_STATE` varchar(32) DEFAULT NULL,
  `COL_STATION_CALLSIGN` varchar(32) DEFAULT NULL,
  `COL_STX` int(11) DEFAULT NULL,
  `COL_STX_STRING` varchar(32) DEFAULT NULL,
  `COL_SWL` int(11) DEFAULT NULL,
  `COL_TEN_TEN` int(11) DEFAULT NULL,
  `COL_TIME_OFF` datetime DEFAULT NULL,
  `COL_TIME_ON` datetime DEFAULT NULL,
  `COL_TX_PWR` double DEFAULT NULL,
  `COL_WEB` varchar(128) DEFAULT NULL,
  `COL_USER_DEFINED_0` varchar(64) DEFAULT NULL,
  `COL_USER_DEFINED_1` varchar(64) DEFAULT NULL,
  `COL_USER_DEFINED_2` varchar(64) DEFAULT NULL,
  `COL_USER_DEFINED_3` varchar(64) DEFAULT NULL,
  `COL_USER_DEFINED_4` varchar(64) DEFAULT NULL,
  `COL_USER_DEFINED_5` varchar(64) DEFAULT NULL,
  `COL_USER_DEFINED_6` varchar(64) DEFAULT NULL,
  `COL_USER_DEFINED_7` varchar(64) DEFAULT NULL,
  `COL_USER_DEFINED_8` varchar(64) DEFAULT NULL,
  `COL_USER_DEFINED_9` varchar(64) DEFAULT NULL,
  `COL_CREDIT_GRANTED` varchar(64) DEFAULT NULL,
  `COL_CREDIT_SUBMITTED` varchar(64) DEFAULT NULL,
  `COL_ADDRESS_INTL` varchar(255) DEFAULT NULL,
  `COL_AWARD_GRANTED` varchar(255) DEFAULT NULL,
  `COL_AWARD_SUMMITED` varchar(255) DEFAULT NULL,
  `COL_CLUBLOG_QSO_UPLOAD_DATE` datetime DEFAULT NULL,
  `COL_CLUBLOG_QSO_UPLOAD_STATUS` varchar(20) DEFAULT NULL,
  `COL_COMMENT_INTL` varchar(255) DEFAULT NULL,
  `COL_COUNTRY_INTL` varchar(255) DEFAULT NULL,
  `COL_SILENT_KEY` varchar(2) DEFAULT NULL,
  `COL_SKCC` varchar(255) DEFAULT NULL,
  `COL_DARC_DOK` varchar(10) DEFAULT NULL,
  `COL_FISTS` int(10) DEFAULT NULL,
  `COL_FISTS_CC` int(10) DEFAULT NULL,
  `COL_HRDLOG_QSO_UPLOAD_DATE` datetime DEFAULT NULL,
  `COL_HRDLOG_QSO_UPLOAD_STATUS` varchar(10) DEFAULT NULL,
  `COL_MY_ANTENNA` varchar(255) DEFAULT NULL,
  `COL_MY_ANTENNA_INTL` varchar(255) DEFAULT NULL,
  `COL_MY_CITY_INTL` varchar(255) DEFAULT NULL,
  `COL_MY_COUNTRY_INTL` int(6) DEFAULT NULL,
  `COL_MY_DXCC` int(6) DEFAULT NULL,
  `COL_MY_FISTS` int(10) DEFAULT NULL,
  `COL_MY_IOTA_ISLAND_ID` varchar(10) DEFAULT NULL,
  `COL_MY_NAME_INTL` varchar(255) DEFAULT NULL,
  `COL_MY_POSTCODE_INTL` varchar(255) DEFAULT NULL,
  `COL_MY_RIG_INTL` varchar(255) DEFAULT NULL,
  `COL_MY_SIG_INTL` varchar(255) DEFAULT NULL,
  `COL_MY_SIG_INFO_INTL` varchar(255) DEFAULT NULL,
  `COL_MY_SOTA_REF` varchar(50) DEFAULT NULL,
  `COL_MY_STREET_INTL` varchar(255) DEFAULT NULL,
  `COL_MY_USACA_COUNTIES` varchar(255) DEFAULT NULL,
  `COL_MY_VUCC_GRIDS` varchar(50) DEFAULT NULL,
  `COL_NAME_INTL` varchar(255) DEFAULT NULL,
  `COL_NOTES_INTL` longtext DEFAULT NULL,
  `COL_QRZCOM_QSO_UPLOAD_DATE` datetime DEFAULT NULL,
  `COL_QRZCOM_QSO_UPLOAD_STATUS` varchar(10) DEFAULT NULL,
  `COL_QSO_DATE` date DEFAULT NULL,
  `COL_QSO_DATE_OFF` date DEFAULT NULL,
  `COL_QTH_INTL` varchar(255) DEFAULT NULL,
  `COL_REGION` varchar(25) DEFAULT NULL,
  `COL_RIG_INTL` varchar(255) DEFAULT NULL,
  `COL_SIG_INTL` varchar(255) DEFAULT NULL,
  `COL_SIG_INFO_INTL` varchar(255) DEFAULT NULL,
  `COL_SOTA_REF` varchar(30) DEFAULT NULL,
  `COL_SUBMODE` varchar(25) DEFAULT NULL,
  `COL_UKSMG` varchar(64) DEFAULT NULL,
  `COL_USACA_COUNTIES` varchar(255) DEFAULT NULL,
  `COL_VUCC_GRIDS` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`COL_PRIMARY_KEY`),
  KEY `HRD_IDX_COL_BAND` (`COL_BAND`),
  KEY `HRD_IDX_COL_CALL` (`COL_CALL`),
  KEY `HRD_IDX_COL_CONT` (`COL_CONT`),
  KEY `HRD_IDX_COL_DXCC` (`COL_DXCC`),
  KEY `HRD_IDX_COL_IOTA` (`COL_IOTA`),
  KEY `HRD_IDX_COL_MODE` (`COL_MODE`),
  KEY `HRD_IDX_COL_PFX` (`COL_PFX`),
  KEY `HRD_IDX_COL_TIME_ON` (`COL_TIME_ON`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
-- Records of TABLE_HRD_CONTACTS_V01
-- ----------------------------

DROP TABLE IF EXISTS `options`;
CREATE TABLE `options` (
  `option_id` bigint(20) UNSIGNED NOT NULL,
  `option_name` varchar(191) DEFAULT NULL,
  `option_value` longtext NOT NULL,
  `autoload` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `options`
  ADD PRIMARY KEY (`option_id`),
  ADD UNIQUE KEY `option_name` (`option_name`);

ALTER TABLE `options`
  MODIFY `option_id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

-- 
-- Dumping data for table `options` that stops the version2 trigger from firing
INSERT INTO `options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES (NULL, 'version2_trigger', 'true', 'yes');

-- ----------------------------
-- Table structure for timezones
-- ----------------------------
DROP TABLE IF EXISTS `timezones`;
CREATE TABLE `timezones` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`name` varchar(120) COLLATE utf8mb4_bin NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ----------------------------
-- Records of timezones
-- ----------------------------
INSERT INTO `timezones` (`id`, `name`) VALUES
(1, 'Africa/Abidjan'),
(2, 'Africa/Accra'),
(3, 'Africa/Addis_Ababa'),
(4, 'Africa/Algiers'),
(5, 'Africa/Asmara'),
(6, 'Africa/Bamako'),
(7, 'Africa/Bangui'),
(8, 'Africa/Banjul'),
(9, 'Africa/Bissau'),
(10, 'Africa/Blantyre'),
(11, 'Africa/Brazzaville'),
(12, 'Africa/Bujumbura'),
(13, 'Africa/Cairo'),
(14, 'Africa/Casablanca'),
(15, 'Africa/Ceuta'),
(16, 'Africa/Conakry'),
(17, 'Africa/Dakar'),
(18, 'Africa/Dar_es_Salaam'),
(19, 'Africa/Djibouti'),
(20, 'Africa/Douala'),
(21, 'Africa/El_Aaiun'),
(22, 'Africa/Freetown'),
(23, 'Africa/Gaborone'),
(24, 'Africa/Harare'),
(25, 'Africa/Johannesburg'),
(26, 'Africa/Juba'),
(27, 'Africa/Kampala'),
(28, 'Africa/Khartoum'),
(29, 'Africa/Kigali'),
(30, 'Africa/Kinshasa'),
(31, 'Africa/Lagos'),
(32, 'Africa/Libreville'),
(33, 'Africa/Lome'),
(34, 'Africa/Luanda'),
(35, 'Africa/Lubumbashi'),
(36, 'Africa/Lusaka'),
(37, 'Africa/Malabo'),
(38, 'Africa/Maputo'),
(39, 'Africa/Maseru'),
(40, 'Africa/Mbabane'),
(41, 'Africa/Mogadishu'),
(42, 'Africa/Monrovia'),
(43, 'Africa/Nairobi'),
(44, 'Africa/Ndjamena'),
(45, 'Africa/Niamey'),
(46, 'Africa/Nouakchott'),
(47, 'Africa/Ouagadougou'),
(48, 'Africa/Porto-Novo'),
(49, 'Africa/Sao_Tome'),
(50, 'Africa/Tripoli'),
(51, 'Africa/Tunis'),
(52, 'Africa/Windhoek'),
(53, 'America/Adak'),
(54, 'America/Anchorage'),
(55, 'America/Anguilla'),
(56, 'America/Antigua'),
(57, 'America/Araguaina'),
(58, 'America/Argentina/Buenos_Aires'),
(59, 'America/Argentina/Catamarca'),
(60, 'America/Argentina/Cordoba'),
(61, 'America/Argentina/Jujuy'),
(62, 'America/Argentina/La_Rioja'),
(63, 'America/Argentina/Mendoza'),
(64, 'America/Argentina/Rio_Gallegos'),
(65, 'America/Argentina/Salta'),
(66, 'America/Argentina/San_Juan'),
(67, 'America/Argentina/San_Luis'),
(68, 'America/Argentina/Tucuman'),
(69, 'America/Argentina/Ushuaia'),
(70, 'America/Aruba'),
(71, 'America/Asuncion'),
(72, 'America/Atikokan'),
(73, 'America/Bahia_Banderas'),
(74, 'America/Bahia'),
(75, 'America/Barbados'),
(76, 'America/Belem'),
(77, 'America/Belize'),
(78, 'America/Blanc-Sablon'),
(79, 'America/Boa_Vista'),
(80, 'America/Bogota'),
(81, 'America/Boise'),
(82, 'America/Cambridge_Bay'),
(83, 'America/Campo_Grande'),
(84, 'America/Cancun'),
(85, 'America/Caracas'),
(86, 'America/Cayenne'),
(87, 'America/Cayman'),
(88, 'America/Chicago'),
(89, 'America/Chihuahua'),
(90, 'America/Ciudad_Juarez'),
(91, 'America/Costa_Rica'),
(92, 'America/Creston'),
(93, 'America/Cuiaba'),
(94, 'America/Curacao'),
(95, 'America/Danmarkshavn'),
(96, 'America/Dawson'),
(97, 'America/Dawson_Creek'),
(98, 'America/Denver'),
(99, 'America/Detroit'),
(100, 'America/Dominica'),
(101, 'America/Edmonton'),
(102, 'America/Eirunepe'),
(103, 'America/El_Salvador'),
(104, 'America/Fortaleza'),
(105, 'America/Fort_Nelson'),
(106, 'America/Glace_Bay'),
(107, 'America/Goose_Bay'),
(108, 'America/Grand_Turk'),
(109, 'America/Grenada'),
(110, 'America/Guadeloupe'),
(111, 'America/Guatemala'),
(112, 'America/Guayaquil'),
(113, 'America/Guyana'),
(114, 'America/Halifax'),
(115, 'America/Havana'),
(116, 'America/Hermosillo'),
(117, 'America/Indiana/Indianapolis'),
(118, 'America/Indiana/Knox'),
(119, 'America/Indiana/Marengo'),
(120, 'America/Indiana/Petersburg'),
(121, 'America/Indiana/Tell_City'),
(122, 'America/Indiana/Vevay'),
(123, 'America/Indiana/Vincennes'),
(124, 'America/Indiana/Winamac'),
(125, 'America/Inuvik'),
(126, 'America/Iqaluit'),
(127, 'America/Jamaica'),
(128, 'America/Juneau'),
(129, 'America/Kentucky/Louisville'),
(130, 'America/Kentucky/Monticello'),
(131, 'America/Kralendijk'),
(132, 'America/La_Paz'),
(133, 'America/Lima'),
(134, 'America/Los_Angeles'),
(135, 'America/Lower_Princes'),
(136, 'America/Maceio'),
(137, 'America/Managua'),
(138, 'America/Manaus'),
(139, 'America/Marigot'),
(140, 'America/Martinique'),
(141, 'America/Matamoros'),
(142, 'America/Mazatlan'),
(143, 'America/Menominee'),
(144, 'America/Merida'),
(145, 'America/Metlakatla'),
(146, 'America/Mexico_City'),
(147, 'America/Miquelon'),
(148, 'America/Moncton'),
(149, 'America/Monterrey'),
(150, 'America/Montevideo'),
(151, 'America/Montserrat'),
(152, 'America/Nassau'),
(153, 'America/New_York'),
(154, 'America/Nome'),
(155, 'America/Noronha'),
(156, 'America/North_Dakota/Beulah'),
(157, 'America/North_Dakota/Center'),
(158, 'America/North_Dakota/New_Salem'),
(159, 'America/Nuuk'),
(160, 'America/Ojinaga'),
(161, 'America/Panama'),
(162, 'America/Paramaribo'),
(163, 'America/Phoenix'),
(164, 'America/Port-au-Prince'),
(165, 'America/Port_of_Spain'),
(166, 'America/Porto_Velho'),
(167, 'America/Puerto_Rico'),
(168, 'America/Punta_Arenas'),
(169, 'America/Rankin_Inlet'),
(170, 'America/Recife'),
(171, 'America/Regina'),
(172, 'America/Resolute'),
(173, 'America/Rio_Branco'),
(174, 'America/Santarem'),
(175, 'America/Santiago'),
(176, 'America/Santo_Domingo'),
(177, 'America/Sao_Paulo'),
(178, 'America/Scoresbysund'),
(179, 'America/Sitka'),
(180, 'America/St_Barthelemy'),
(181, 'America/St_Johns'),
(182, 'America/St_Kitts'),
(183, 'America/St_Lucia'),
(184, 'America/St_Thomas'),
(185, 'America/St_Vincent'),
(186, 'America/Swift_Current'),
(187, 'America/Tegucigalpa'),
(188, 'America/Thule'),
(189, 'America/Tijuana'),
(190, 'America/Toronto'),
(191, 'America/Tortola'),
(192, 'America/Vancouver'),
(193, 'America/Whitehorse'),
(194, 'America/Winnipeg'),
(195, 'America/Yakutat'),
(196, 'Antarctica/Casey'),
(197, 'Antarctica/Davis'),
(198, 'Antarctica/DumontDUrville'),
(199, 'Antarctica/Macquarie'),
(200, 'Antarctica/Mawson'),
(201, 'Antarctica/McMurdo'),
(202, 'Antarctica/Palmer'),
(203, 'Antarctica/Rothera'),
(204, 'Antarctica/Syowa'),
(205, 'Antarctica/Troll'),
(206, 'Antarctica/Vostok'),
(207, 'Arctic/Longyearbyen'),
(208, 'Asia/Aden'),
(209, 'Asia/Almaty'),
(210, 'Asia/Amman'),
(211, 'Asia/Anadyr'),
(212, 'Asia/Aqtau'),
(213, 'Asia/Aqtobe'),
(214, 'Asia/Ashgabat'),
(215, 'Asia/Atyrau'),
(216, 'Asia/Baghdad'),
(217, 'Asia/Bahrain'),
(218, 'Asia/Baku'),
(219, 'Asia/Bangkok'),
(220, 'Asia/Barnaul'),
(221, 'Asia/Beirut'),
(222, 'Asia/Bishkek'),
(223, 'Asia/Brunei'),
(224, 'Asia/Chita'),
(225, 'Asia/Colombo'),
(226, 'Asia/Damascus'),
(227, 'Asia/Dhaka'),
(228, 'Asia/Dili'),
(229, 'Asia/Dubai'),
(230, 'Asia/Dushanbe'),
(231, 'Asia/Famagusta'),
(232, 'Asia/Gaza'),
(233, 'Asia/Hebron'),
(234, 'Asia/Ho_Chi_Minh'),
(235, 'Asia/Hong_Kong'),
(236, 'Asia/Hovd'),
(237, 'Asia/Irkutsk'),
(238, 'Asia/Jakarta'),
(239, 'Asia/Jayapura'),
(240, 'Asia/Jerusalem'),
(241, 'Asia/Kabul'),
(242, 'Asia/Kamchatka'),
(243, 'Asia/Karachi'),
(244, 'Asia/Kathmandu'),
(245, 'Asia/Khandyga'),
(246, 'Asia/Kolkata'),
(247, 'Asia/Krasnoyarsk'),
(248, 'Asia/Kuala_Lumpur'),
(249, 'Asia/Kuching'),
(250, 'Asia/Kuwait'),
(251, 'Asia/Macau'),
(252, 'Asia/Magadan'),
(253, 'Asia/Makassar'),
(254, 'Asia/Manila'),
(255, 'Asia/Muscat'),
(256, 'Asia/Nicosia'),
(257, 'Asia/Novokuznetsk'),
(258, 'Asia/Novosibirsk'),
(259, 'Asia/Omsk'),
(260, 'Asia/Oral'),
(261, 'Asia/Phnom_Penh'),
(262, 'Asia/Pontianak'),
(263, 'Asia/Pyongyang'),
(264, 'Asia/Qatar'),
(265, 'Asia/Qostanay'),
(266, 'Asia/Qyzylorda'),
(267, 'Asia/Riyadh'),
(268, 'Asia/Sakhalin'),
(269, 'Asia/Samarkand'),
(270, 'Asia/Seoul'),
(271, 'Asia/Shanghai'),
(272, 'Asia/Singapore'),
(273, 'Asia/Srednekolymsk'),
(274, 'Asia/Taipei'),
(275, 'Asia/Tashkent'),
(276, 'Asia/Tbilisi'),
(277, 'Asia/Tehran'),
(278, 'Asia/Thimphu'),
(279, 'Asia/Tokyo'),
(280, 'Asia/Tomsk'),
(281, 'Asia/Ulaanbaatar'),
(282, 'Asia/Urumqi'),
(283, 'Asia/Ust-Nera'),
(284, 'Asia/Vientiane'),
(285, 'Asia/Vladivostok'),
(286, 'Asia/Yakutsk'),
(287, 'Asia/Yangon'),
(288, 'Asia/Yekaterinburg'),
(289, 'Asia/Yerevan'),
(290, 'Atlantic/Azores'),
(291, 'Atlantic/Bermuda'),
(292, 'Atlantic/Canary'),
(293, 'Atlantic/Cape_Verde'),
(294, 'Atlantic/Faroe'),
(295, 'Atlantic/Madeira'),
(296, 'Atlantic/Reykjavik'),
(297, 'Atlantic/South_Georgia'),
(298, 'Atlantic/Stanley'),
(299, 'Atlantic/St_Helena'),
(300, 'Australia/Adelaide'),
(301, 'Australia/Brisbane'),
(302, 'Australia/Broken_Hill'),
(303, 'Australia/Darwin'),
(304, 'Australia/Eucla'),
(305, 'Australia/Hobart'),
(306, 'Australia/Lindeman'),
(307, 'Australia/Lord_Howe'),
(308, 'Australia/Melbourne'),
(309, 'Australia/Perth'),
(310, 'Australia/Sydney'),
(311, 'Europe/Amsterdam'),
(312, 'Europe/Andorra'),
(313, 'Europe/Astrakhan'),
(314, 'Europe/Athens'),
(315, 'Europe/Belgrade'),
(316, 'Europe/Berlin'),
(317, 'Europe/Bratislava'),
(318, 'Europe/Brussels'),
(319, 'Europe/Bucharest'),
(320, 'Europe/Budapest'),
(321, 'Europe/Busingen'),
(322, 'Europe/Chisinau'),
(323, 'Europe/Copenhagen'),
(324, 'Europe/Dublin'),
(325, 'Europe/Gibraltar'),
(326, 'Europe/Guernsey'),
(327, 'Europe/Helsinki'),
(328, 'Europe/Isle_of_Man'),
(329, 'Europe/Istanbul'),
(330, 'Europe/Jersey'),
(331, 'Europe/Kaliningrad'),
(332, 'Europe/Kirov'),
(333, 'Europe/Kyiv'),
(334, 'Europe/Lisbon'),
(335, 'Europe/Ljubljana'),
(336, 'Europe/London'),
(337, 'Europe/Luxembourg'),
(338, 'Europe/Madrid'),
(339, 'Europe/Malta'),
(340, 'Europe/Mariehamn'),
(341, 'Europe/Minsk'),
(342, 'Europe/Monaco'),
(343, 'Europe/Moscow'),
(344, 'Europe/Oslo'),
(345, 'Europe/Paris'),
(346, 'Europe/Podgorica'),
(347, 'Europe/Prague'),
(348, 'Europe/Riga'),
(349, 'Europe/Rome'),
(350, 'Europe/Samara'),
(351, 'Europe/San_Marino'),
(352, 'Europe/Sarajevo'),
(353, 'Europe/Saratov'),
(354, 'Europe/Simferopol'),
(355, 'Europe/Skopje'),
(356, 'Europe/Sofia'),
(357, 'Europe/Stockholm'),
(358, 'Europe/Tallinn'),
(359, 'Europe/Tirane'),
(360, 'Europe/Ulyanovsk'),
(361, 'Europe/Vaduz'),
(362, 'Europe/Vatican'),
(363, 'Europe/Vienna'),
(364, 'Europe/Vilnius'),
(365, 'Europe/Volgograd'),
(366, 'Europe/Warsaw'),
(367, 'Europe/Zagreb'),
(368, 'Europe/Zurich'),
(369, 'Indian/Antananarivo'),
(370, 'Indian/Chagos'),
(371, 'Indian/Christmas'),
(372, 'Indian/Cocos'),
(373, 'Indian/Comoro'),
(374, 'Indian/Kerguelen'),
(375, 'Indian/Mahe'),
(376, 'Indian/Maldives'),
(377, 'Indian/Mauritius'),
(378, 'Indian/Mayotte'),
(379, 'Indian/Reunion'),
(380, 'Pacific/Apia'),
(381, 'Pacific/Auckland'),
(382, 'Pacific/Bougainville'),
(383, 'Pacific/Chatham'),
(384, 'Pacific/Chuuk'),
(385, 'Pacific/Easter'),
(386, 'Pacific/Efate'),
(387, 'Pacific/Fakaofo'),
(388, 'Pacific/Fiji'),
(389, 'Pacific/Funafuti'),
(390, 'Pacific/Galapagos'),
(391, 'Pacific/Gambier'),
(392, 'Pacific/Guadalcanal'),
(393, 'Pacific/Guam'),
(394, 'Pacific/Honolulu'),
(395, 'Pacific/Kanton'),
(396, 'Pacific/Kiritimati'),
(397, 'Pacific/Kosrae'),
(398, 'Pacific/Kwajalein'),
(399, 'Pacific/Majuro'),
(400, 'Pacific/Marquesas'),
(401, 'Pacific/Midway'),
(402, 'Pacific/Nauru'),
(403, 'Pacific/Niue'),
(404, 'Pacific/Norfolk'),
(405, 'Pacific/Noumea'),
(406, 'Pacific/Pago_Pago'),
(407, 'Pacific/Palau'),
(408, 'Pacific/Pitcairn'),
(409, 'Pacific/Pohnpei'),
(410, 'Pacific/Port_Moresby'),
(411, 'Pacific/Rarotonga'),
(412, 'Pacific/Saipan'),
(413, 'Pacific/Tahiti'),
(414, 'Pacific/Tarawa'),
(415, 'Pacific/Tongatapu'),
(416, 'Pacific/Wake'),
(417, 'Pacific/Wallis');

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Unique user ID',
  `user_name` varchar(32) NOT NULL COMMENT 'Username',
  `user_password` varchar(64) NOT NULL COMMENT 'Password',
  `user_email` varchar(64) NOT NULL COMMENT 'E-mail address',
  `user_type` varchar(8) NOT NULL COMMENT 'User type',
  `user_callsign` varchar(32) NOT NULL COMMENT 'User''s callsign',
  `user_locator` varchar(16) NOT NULL COMMENT 'User''s locator',
  `user_firstname` varchar(32) NOT NULL COMMENT 'User''s first name',
  `user_lastname` varchar(32) NOT NULL COMMENT 'User''s last name',
  `user_timezone` int(3) NOT NULL DEFAULT 0,
  `user_lotw_name` varchar(32) DEFAULT NULL,
  `user_lotw_password` varchar(64) DEFAULT NULL,
  `user_eqsl_name` varchar(32) DEFAULT NULL,
  `user_eqsl_password` varchar(64) DEFAULT NULL,
  `user_eqsl_qth_nickname` varchar(32) DEFAULT NULL,
  `active_station_logbook` int(11) DEFAULT NULL,
  `user_show_log_utc` int(11) DEFAULT NULL,
  `language` varchar(32) default 'english',
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `user_name` (`user_name`),
  UNIQUE KEY `user_email` (`user_email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO `users` VALUES ('1', '%%FIRSTUSER_NAME%%', '%%FIRSTUSER_PASS%%', '%%FIRSTUSER_MAIL%%', '99', '%%FIRSTUSER_CALL%%', '%%FIRSTUSER_LOCATOR%%', '%%FIRSTUSER_FIRSTNAME%%', '%%FIRSTUSER_LASTNAME%%', '%%FIRSTUSER_TIMEZONE%%', null, null, null, null, null, 1, 1, '%%FIRSTUSER_USERLANGUAGE%%');

-- ----------------------------
-- Records of station_logbooks
-- ----------------------------
INSERT INTO `station_logbooks` VALUES ('1', '1', '%%FIRSTUSER_CITY%%', null, null, 0);

-- ----------------------------
-- Records of station_profile
-- ----------------------------
INSERT INTO `station_profile` VALUES (
'1',
'%%FIRSTUSER_CITY%%',
'%%FIRSTUSER_LOCATOR%%',
'%%FIRSTUSER_CITY%%',
'',
'',
'%%FIRSTUSER_CALL%%',
null,
'%%FIRSTUSER_DXCC%%',
'',
'1',
'1',
'1',
'',
'',
'',
'',
'',
'',
'0',
'1',
'',
'',
'0',
'',
'0',
'',
'https://qo100dx.club/api',
'0',
'0',
'0',
'',
'');

-- ----------------------------
-- Records of station_logbooks_relationship
-- ----------------------------
INSERT INTO `station_logbooks_relationship` VALUES ('1', '1', '1', now());

DROP TABLE IF EXISTS `dxcc_entities`;
CREATE TABLE `dxcc_entities` (
  `adif` smallint(6) NOT NULL,
  `name` varchar(150) DEFAULT NULL,
  `prefix` varchar(32) NOT NULL,
  `cqz` smallint(6) NOT NULL,
  `ituz` smallint(6) NOT NULL,
  `cont` varchar(5) NOT NULL,
  `long` float NOT NULL,
  `lat` float NOT NULL,
  `end` date DEFAULT NULL,
  `start` date DEFAULT NULL,
  PRIMARY KEY (`adif`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `dxcc_exceptions`;
CREATE TABLE `dxcc_exceptions` (
  `record` int(11) NOT NULL,
  `call` varchar(32) DEFAULT NULL,
  `entity` varchar(255) NOT NULL,
  `adif` smallint(6) NOT NULL,
  `cqz` smallint(6) NOT NULL,
  `cont` varchar(5) NOT NULL,
  `long` float NOT NULL,
  `lat` float NOT NULL,
  `start` date DEFAULT NULL,
  `end` date DEFAULT NULL,
  PRIMARY KEY (`record`),
  KEY `idx_dxcc_exceptions_logic` (`call`,`start`,`end`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `dxcc_prefixes`;
CREATE TABLE `dxcc_prefixes` (
  `record` int(11) NOT NULL,
  `call` varchar(32) DEFAULT NULL,
  `entity` varchar(255) NOT NULL,
  `adif` smallint(6) NOT NULL,
  `cqz` smallint(6) NOT NULL,
  `cont` varchar(5) NOT NULL,
  `long` float NOT NULL,
  `lat` float NOT NULL,
  `start` date DEFAULT NULL,
  `end` date DEFAULT NULL,
  PRIMARY KEY (`record`),
  KEY `idx_dxcc_prefixes_logic` (`call`,`start`,`end`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
